activeloopai/deeplake

- hub/exceptions.py
- hub/marray/array.py
- hub/marray/dataset.py
- hub/marray/interface.py
- hub/marray/meta.py
- setup.py
- test/test_datasets.py
Added meta object for info text upload and download
> Dataset abstraction corrected

- hub/features/deserialize.py
- hub/features/serialize.py
- hub/features/tests/test_serilize_deserialize.py
Added support for serialization, deserialization of Primitives, Tensors, and FeatureDicts
> serialization and deserialization added

- .circleci/config.yml
- README.md
- requirements.txt
> Add coverage to CircleCI

- hub/training/model.py
- hub/training/tests/test_model.py
> Store and load models

- .circleci/config.yml
As stated in https://github.com/activeloopai/Hub/issues/62#issuecomment-706685043
> Add PyPi publisher orb

- .circleci/config.yml
> Revert "Add PyPi publisher orb"

- .github/workflows/locust.yaml
Locust is a Python code review tool:
https://github.com/simiotics/locust
> Added Locust GitHub Action

- README.md
- examples/mnist/Colab-demo.md
link for #64 
I have added the link to Colab tutorial at Hub/examples/mnist/Colab-demo.md
> Add Colab-tutorial

- examples/3D Object Dataset/upload.py
- Add the upload.py file for storing the 3D Object data to the hub.
- Formatted with Black
- Add comments and insights regarding dataset 
- Confirmed and cross checked the working of the code 
Please review it and let me know if any nitpicks or changes/suggestions needed.
> add upload.py

- docs/source/concepts/tensor.md
- docs/source/integrations/pytorch.md
- docs/source/integrations/tensorflow.md
- docs/source/simple.md
- docs/source/storage/tutorials.md
- docs/source/tutorials/pytorch.md
- docs/source/why.md
Fixed typos and other mistakes in the documentation. Also changed cases for references to certain packages (e.g. Tensorflow, PyTorch) mentioned in the documentation for greater consistency.
> Resolve errors and change cases in documentation

- examples/coco/upload_coco2017.py
- hub/collections/dataset/core.py
> fixing to_tensorflow method to take any shape #44

- examples/coco/upload_coco2017.py
> Fix Black formatting

- .circleci/config.yml
Add step to push image for `snarkai/hub` to Docker Hub on new tag.
Closes #128.
> feat: add docker hub deployment

- examples/cub200/upload_cub2010.py
Addresses Issue #112. I've added an example of storing the CUB200 (2010) dataset.
> Caltech-UCSD Birds 200

- examples/MPII Human Pose Dataset/mpii_data_upload.py
> issue #106 MPII Human Pose Dataset upload example

- docs/source/concepts/dataset.md
- docs/source/concepts/features.md
- docs/source/index.rst
- docs/source/simple.md
- hub/features/features.py
This patch fixes minor errors in the documentation like spacing, indentation, spelling typos, etc
> Fix minor documentation bugs

- hub/api/dataset.py
Only create entry if needcreate is True
> Minor fix to backend api integration

- hub/api/dataset.py
- hub/api/datasetview.py
- hub/api/tensorview.py
- hub/exceptions.py
- hub/store/dynamic_tensor.py
Replace assertions, remove username exception, add dynamic tensor shape exceptions
> Exceptions

- hub/tests/test_utils.py
> Adds unit test for utils.py

- examples/MPII Human Pose Dataset/mpii_data_upload.py
> Correcting MPII human pose dataset upload.py

- docs/requirements.txt
> Revert "Bump sphinx from 3.1.2 to 3.3.1"

- hub/api/tensorview.py
- hub/api/tests/test_dataset.py
- hub/api/tests/test_tensorview_shapes.py
- hub/store/dynamic_tensor.py
- hub/store/tests/test_dynamic_tensor.py
Simplified get_shape logic, added support for slices directly in dynamic_tensor instead of in wrapper.
> Get shape now directly supports slices

- hub/api/dataset.py
- hub/api/tests/test_dataset.py
- hub/compute/tests/test_transform.py
- hub/store/azure_fs.py
- hub/store/lru_cache.py
- hub/store/store.py
- hub/store/tests/test_lru_cache.py
Previous cache versions have issues with writes not being cached but directly pushed to remote.
This causes slowdowns. 
This manually written version caches everything.
> LRU Cache implemented with cacheable writes

- hub/api/dataset.py
- hub/exceptions.py
> Add user exception

- hub/api/tests/test_tensorview.py
> Add tests for api/tensorview.py

- hub/features/tests/test_features.py
- hub/features/tests/test_tensor.py
> Add tests for features/features.py

- docs/source/api.md
- docs/source/concepts/transform.md
- docs/source/installing.md
- docs/source/integrations/tensorflow.md
- docs/source/simple.md
Change version, commits, pipelines
> Documentation

- examples/upload_tfds.py
- hub/client/base.py
> error msg change

- hub/schema/class_label.py
- hub/schema/deserialize.py
Fixes ClassLabel name losses after deserialization of class_labels
> fixed ClassLabel deserialization

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Fixed Issue #274, hence three templates for:
- PR
- Issue
- Feature Request
are provided
> Fixed Issue #274, Three templates for:  - PR - Issue - Feature Request

- hub/api/tensorview.py
- hub/api/tests/test_dataset.py
- hub/compute/transform.py
- hub/store/dynamic_tensor.py
- test/benchmark/transform_benchmarks/from_tfds.py
Changes how shapes are set for slices in transform. Transforms now 3x faster than before.
Also fixes automatic sample size detection.
Also added basic benchmark for transforms that uses from_tfds on mock coco data.
Benchmarks:-
> Optimizations to transform

- README.md
- examples/basic.py
Here is the fix for documentation page and basic.py file.
> fix doc & basic.py in Hub

- CONTRIBUTING.md
Additional instructions for beginner contributors.
> Contrib guidelines

- .flake8
- hub/api/tests/test_dataset.py
- hub/store/shape_detector.py
- hub/store/tests/test_shape_detector.py
> Exceptions added to validate from input to Tensor schema

- hub/schema/segmentation.py
- hub/schema/tests/test_features.py
Fixes an issue faced by user while trying to print dataset containing segmentation
> Fixed segmentation and added more feature tests

- hub/api/dataset.py
- hub/compute/transform.py
> private transforms

- .github/ISSUE_TEMPLATE/feature_request.md
Adding a label for automatic labeling new features as "enhancement"
> Adding the label "enhancement"

- examples/Quick Start Tutorial.ipynb
Initial collection of notebooks for absolute beginners
> Include notebooks for absolute beginners to Hub

- hub/api/dataset.py
- hub/api/dataset_utils.py
- hub/api/datasetview.py
- hub/api/tensorview.py
- hub/api/tests/test_dataset.py
- hub/compute/ray.py
- hub/compute/tests/test_ray.py
- hub/store/dynamic_tensor.py
Fixed the issue with setting dynamic arrays that have shape=[] e.g. numpy.array("sometext")
> fix for dynamic setting shapes

- hub/api/dataset.py
- hub/api/tests/test_dataset.py
- hub/schema/features.py
- hub/schema/tests/test_tensor.py
More checks added so that user doesn't face problems during dataset creation
> More checks for tensor shapes and max_shapes

- benchmarks/README.md
Content:
- PNG Compression (no charts yet)
> Add readme to benchmarks

- hub/api/dataset.py
- hub/api/tests/test_converters.py
- hub/api/tests/test_dataset.py
- hub/compute/transform.py
- hub/schema/audio.py
- hub/schema/bbox.py
- hub/schema/class_label.py
- hub/schema/image.py
- hub/schema/mask.py
- hub/schema/polygon.py
- hub/schema/segmentation.py
- hub/schema/sequence.py
- hub/schema/tests/test_features.py
- hub/schema/tests/test_serialize_deserialize.py
- hub/schema/text.py
- hub/schema/video.py
- hub/store/dynamic_tensor.py
- hub/tests/test_exceptions.py
Improves test coverage, fixed a couple of small bugs found along the way, and removes unused code.
> Improved test coverage

- hub/api/dataset.py
- hub/api/tests/test_converters.py
Solves #452. 
We need a better fix for this, I've added a check for the Dataset mode which should solve it temporarily however the default mode in which a dataset is opened by non-owner is append, which should be changed to read.
> Hotfix for to_pytorch

- CONTRIBUTORS.rst
We'd like to give credit to those who contribute, whether code or data :-)
> Credit to contributors

- hub/api/dataset.py
Added check for operating system before load. There could be cleaner solutions.
> Fix for bug on windows when loading dataset

- README.md
- README_CN.md
Add Chinese README and a link in the original README to it.
Note: some words remain in English since they are proper nouns or there are no corresponding Chinese word to them.
> README in Chinese

- examples/dataset_endpoint_minio.py
- hub/api/tests/test_dataset.py
- hub/store/store.py
- hub/utils.py
Support for minio and other endpoints. Added an example for the same.
> Support for minio added

- examples/download_cola.py
Include an example demonstrating how to download and push CoLA dataset.
> Include script to fetch CoLA dataset in examples

- ROADMAP.md
[Hub's development roadmap](https://github.com/activeloopai/Hub/projects/10) for 2021. 
**- What is this?** A way to organize and prioritize feature requests and development.
**- Who is this for?** The entire Hub community, including users and contributors.
> Development Roadmap

- benchmarks/README.md
- benchmarks/benchmark_dataset_comparison.py
- benchmarks/benchmark_run.sh
- benchmarks/benchmark_setup.sh
- benchmarks/benchmark_tiledb_hub.py
- requirements-benchmarks.txt
Add reproducible benchmarks with a README.
> Add benchmarks

- examples/nlp_using_hub.ipynb
Closes #536. This is the converted notebook from a  Colab to Jupyter environment.
> hub and huggingface transformers tutorial added.

- hub/api/dataset.py
- hub/api/datasetview.py
- hub/api/tests/test_converters.py
Fixes to_tensorflow for datasets with dictionaries inside tensors #532
Also updates some outdated docstrings of the converters.
> Fixes to_tensorflow bug

- examples/nlp_using_hub.ipynb
- examples/tutorial/Tutorial 1a - Uploading Images.ipynb
- examples/tutorial/Tutorial 1b - Uploading Dataframes.ipynb
- examples/tutorial/Tutorial 1c - Uploading Audio.ipynb
- examples/tutorial/Tutorial 2 - Retrieving Remote Data.ipynb
- examples/tutorial/Tutorial 3 - Transforming Data.ipynb
- examples/tutorial/Tutorial 4 - What are Dynamic Tensors.ipynb
Updated the example notebooks with pip install also added reason in the comment for FileNotFoundError.
> update example notebooks with pip

- docs/source/simple.md
**Reference Issues**
None
**What does this fix?**
These are some minor doc fixes that I found while reading through the site
> Minor Documentation fixes

- .github/workflows/package.yml
Adding a dependency that `test_with_optional` only runs, if `test` was successful.
> Fixed Issue: #599

- docs/source/simple.md
Refers to https://github.com/activeloopai/Hub/issues/603
> Add MinIO to Data Storage docs

- README.md
- README_CN.md
- README_KR.md
- README_TR.md
Translated the readme file into Korean.
> Add README_KR.md

- .github/ISSUE_TEMPLATE/feature_request.md
Hey! I saw #373 and made a pull request to fix it
> fixed issue template bug #373

- README.md
Notify users that Hub collects anonymized usage data.
> include consent language in readme

- benchmarks/genomelake_hub_backend.ipynb
Added Hub backend to package: "genomelake" and wrote code for benchmarking performance against pre-existing TileDB backend.
> Added genomelake hub backend benchmarks

- hub/client/base.py
#365,I have solved this issue.
> avoided mutable  default args in client/base.py

- setup.py
Removed Version related information in setup file to resolve #669
> Removed version information in setup.py

- setup.py
> Revert "Removed version information in setup.py"

- benchmarks/webdataset_hub_benchmarks.ipynb
This ipynb notebook consists of benchmarks of read access overhead for Hub and WebDataset. @haiyangdeperci tagging for review.
> Added WebDataset Hub benchmarks

- setup.py
> Prevent internal imports in setup

- .circleci/config.yml
- benchmarks/webdataset_hub_benchmarks.ipynb
- meta.yaml
- setup.py
This PR uses a more optimal hub version for the setup and adds a remote Hub results.
> Restructure webdataset benchmark setup and add new results

- hub/api/integrations.py
Reverts a change made to to_pytorch that slowed down iteration
> Hotfix for pytorch active chunk range

- hub/api/dataset.py
- hub/client/hub_control.py
- hub/defaults.py
- hub/store/s3_file_system_replacement.py
- hub/store/s3_storage.py
- hub/store/store.py
Fixes issues with credentials getting expired by fetching new credentials after expiry on the fly.
Haven't been able to cover some parts of the code with tests as it requires a timeout that happens after 10 hours
> Fixes issues with credentials getting expired

- docs/requirements.txt
> Revert "Bump docutils from 0.16 to 0.17.1"

- requirements-optional.txt
This PR fixed issue #797 by removing `ray>=1.0`.
> Update requirements-optional for fix issue #797

- hub/api/tests/test_dataset.py
> Fix issue #778

- .gitignore
This PR updated the [.gitignore](https://github.com/activeloopai/Hub/blob/master/.gitignore) for `.dccache` files.
```shell
######################
.dccache
.DS_Store?
ehthumbs.db
Icon?
Thumbs.db
```
> Update .gitignore for .ddcache

- hub/core/chunk_engine/exceptions.py
- hub/core/chunk_engine/generator.py
- hub/util/exceptions.py
I need to add a bunch of exceptions for #825 and I think it's best if we have them all in one place going forward.
I also changed up the naming for the existing exception for clarity. Let me know if we don't think this is a good change.
> [2.0] Combine exceptions into util

- hub/api/dataset.py
- hub/api/dataset_utils.py
- hub/api/datasetview.py
- hub/api/integrations.py
- hub/api/tests/test_converters.py
- hub/api/tests/test_dataset.py
- hub/auto/tests/test_tabular_data.py
- hub/schema/deserialize.py
- hub/schema/features.py
- hub/schema/serialize.py
- hub/schema/tests/test_serialize_deserialize.py
- hub/store/shape_detector.py
Adds support for pytorch shuffling in Hub.
Also fixes an incorrect schema mismatch error
> Pytorch data shuffling

- .github/workflows/package.yml
---
The GitHub-Action CI/CD is now running full unit and coverage test for all (forked) branches.
> GitHub Action CI/CD - Fixed issue #595

- hub/core/storage/s3.py
- hub/integrations/pytorch.py
- hub/integrations/tests/test_pytorch.py
- requirements/common.txt
Fixes a bug when iterating through a TorchDataset multiple times.
> Fixed Pytorch iteration bug over multiple epochs

- bin/publish_pip.sh
- hub/__init__.py
Added pipy script for releasing the package.
> pipy script

- hub/client/client.py
> Fix None token issue

- README.md
> Update README for Hub V1.md

- requirements/common.txt
This should fix some of the documentation issues we've been experiencing. If anyone has context on how/when it gets generated, let me know so we can verify.
See: https://github.com/bugout-dev/humbug/pull/73
> [2.0] Bump humbug to 0.2.6

- hub/api/dataset.py
- hub/client/client.py
- hub/core/storage/tests/test_storage_provider.py
This is a small PR to add output messages for new `Dataset` creation, existing `Dataset` loading and `Dataset` deletion.
> [2.0] Add necessary messages for dataset operations

- hub/__init__.py
Added init py, otherwise it was throwing an error and updated the version
> added init py

- .circleci/config.yml
Reverts commit b5d80fd22efd31856e96959bf93d9553a6ddc89f. No idea why it was removed in the first place, or if it will pass. Need to open the PR to find out
> [2.0] Add back windows CI tests

- conftest.py
Still need to find a cure for the egregious transform output
Transforms are causing a huge block of logs when running the tests. This PR does not fix the root issue, but disables _all_ log output in tests through `conftest.py`. Even when the transform fix is implemented, this change should still stand as the output of info logs is not valuable to test output by default.
> [2.0] Suppress logs in tests

- README.md
> Adding sunsetting statement to readme

- hub/core/transform/test_transform.py
- hub/core/transform/transform.py
- hub/util/tests/test_transform.py
- hub/util/transform.py
> Add htype, compression to transform

- hub/api/tensor.py
> fix minor docstring

- hub/core/chunk.py
- hub/core/chunk_engine.py
- hub/core/meta/encode/shape.py
- hub/core/meta/encode/tests/test_shape_encoder.py
> quick fix on leak

- hub/api/dataset.py
- hub/util/get_storage_provider.py
> Modify dataset loading message

- conftest.py
> [small] Silence tensorflow logs in tests

- hub/api/tensor.py
- hub/api/tests/test_api.py
https://activeloop.atlassian.net/browse/AL-1196
> Array interface for Tensor

- .github/workflows/release-drafter.yml
---
name: Pull request
about: ""
title: "[PR]"
labels: "i: pull-request, i: needs triage"
assignees: ""
---
> Changed from master to main

- hub/api/tensor.py
- hub/api/tests/test_meta.py
- hub/core/chunk_engine.py
needs #1046 to be merged first
adds subsequent update tests for meta to make sure that everything is properly updated. 
implements a temporary solution to this problem (until we remove cachable). may reduce performance, but not by a lot.
> fix meta non-persistence bug (adds test)

- hub/htypes.py
- pdoc/templates/css.mako
> Update htype docs

- hub/__init__.py
Update version and push to pypi
> version update

- pdoc/templates/config.mako
> Enable search in pdoc

- .circleci/config.yml
This prevents ANY events from being fired from the CI/CD environments.
> BUGGER_OFF=true when running tests in Circle CI.

- hub/api/dataset.py
- hub/core/dataset.py
- Updated Bugout reporting to make more sense with the new dataset API
> Bugout reporting update

- hub/core/chunk.py
- hub/core/chunk_engine.py
- hub/core/meta/encode/base_encoder.py
- hub/core/meta/encode/byte_positions.py
- hub/core/meta/encode/chunk_id.py
- hub/core/meta/encode/shape.py
- hub/core/meta/encode/tests/test_byte_positions_encoder.py
- hub/core/meta/encode/tests/test_chunk_id_encoder.py
- hub/core/meta/encode/tests/test_shape_encoder.py
looks like a big PR, but no new functionality
for chunk ID, shape, and byte positions encoder i wrote a base class that generalizes as much functionality as possible. this will make things easier to optimize / change.
> [refactor] encoders base class

- README.md
> Update code snippets

- hub/api/tests/test_update_samples.py
- hub/core/chunk_engine.py
- hub/core/tensor.py
> Update samples fix

- hub/__init__.py
- requirements/common.txt
- setup.py
Pypi Readme readded and removed additional dependancies.
> Release 2.0.3

- hub/__init__.py
- setup.py
> 2.0.4 release Version update

- hub/api/dataset.py
- hub/core/dataset.py
- hub/core/transform/transform.py
- hub/util/bugout_reporter.py
> Fixed bugout reporting paths and overreporting during Dataset initialization.

- hub/core/transform/transform.py
- hub/util/exceptions.py
- hub/util/transform.py
> Updates transform docstrings/variables to remove usage of the word "transform"

- hub/core/chunk_engine.py
> Backward compat fix

- hub/core/dataset.py
- hub/core/tests/test_locking.py
- hub/tests/dataset_fixtures.py
> DS lock fix

- hub/api/tests/test_update_samples.py
- hub/core/chunk_engine.py
- hub/core/serialize.py
- hub/core/tensor.py
- hub/tests/common.py
https://activeloop.atlassian.net/browse/AL-1264
> Tensor inplace ops

- hub/core/lock.py
> DS locking: atexit release

- hub/requirements/common.txt
- hub/util/auto.py
- hub/util/tests/test_auto.py
> [small-Please approve] fix typo

- hub/__init__.py
> Add Tensor to API reference

- hub/client/utils.py
> [small] client/utils.py: Dont sys.exit on Bad request

- hub/api/tests/test_api.py
- hub/auto/tests/test_ingestion.py
- hub/core/dataset.py
- hub/core/meta/dataset_meta.py
- hub/core/storage/prefetch_lru_cache.py
- hub/core/transform/test_transform.py
- hub/core/transform/transform.py
- hub/integrations/pytorch/pytorch_old.py
- hub/integrations/tests/test_pytorch.py
- hub/integrations/tests/test_tensorflow.py
- hub/util/encoder.py
- hub/util/exceptions.py
- hub/util/remove_cache.py
- hub/util/transform.py
Hierarchical tensors: https://activeloop.atlassian.net/browse/AL-1268
> Hierarchical Tensors

- conftest.py
- hub/client/log.py
> [Small] Fixes logging

- README.md
> Istranic update readme

- hub/core/storage/gcs.py
Fix the redundant GCS bucket naming
> gcs path fix

- hub/api/tests/test_api.py
- hub/core/dataset.py
Fixes https://activeloop.atlassian.net/browse/AL-1388
> Tensor group fixes

- hub/compression.py
Fixes: https://activeloop.slack.com/archives/C01SWE73DR6/p1631849373070200
> Missing compressions fix

- hub/constants.py
- hub/core/chunk_engine.py
- hub/core/dataset.py
- hub/core/version_control/commit_chunk_set.py
- hub/util/keys.py
- hub/util/version_control.py
> Fix version control speed for first commit

- hub/__init__.py
- added `__init__.py` file in version control, was causing release failure
- incremented the version to 2.0.12
> version added

- hub/core/dataset.py
> PyTorch & Tensorflow aliases for datasets

- hub/core/dataset.py
> Revert "PyTorch & Tensorflow aliases for datasets"

- hub/core/compression.py
- hub/requirements/requirements.txt
Change lz4 implementation to numcodecs.
> Change lz4 implementation to numcodecs

- .circleci/config.yml
This PR removed Linux Simple Tests from both `test` and `test-and-deploy` workflows.
> Removing "Linux Simple Test" from all workflows

- hub/api/dataset.py
https://activeloop.atlassian.net/browse/AL-1414
Update docs for hub.ingest per https://activeloop.atlassian.net/browse/AL-1414
> Update docs for hub.ingest

- hub/compression.py
- hub/core/tests/test_compression.py
https://activeloop.atlassian.net/browse/AL-1433 6. List compression types for hub.compression module
> AL-1433 List compression types for hub.compression

- hub/api/dataset.py
- hub/core/fast_forwarding.py
removed template, 3 error message updates with no impact on code
> [tiny] Update error messages

- hub/core/dataset.py
> Added reporting for version control

- hub/core/storage/cachable.py
> Beautify meta .json files

- hub/api/dataset.py
- hub/auto/unstructured/image_classification.py
- hub/core/compression.py
- hub/util/auto.py
- hub/util/exceptions.py
> Fixes issues with kaggle tests after audio merge

- hub/api/dataset.py
- hub/api/tests/test_dataset.py
- hub/core/dataset/dataset.py
> Changing default dataset setting from public to private

- hub/api/dataset.py
- hub/core/dataset/__init__.py
- hub/core/dataset/dataset.py
- hub/core/storage/provider.py
- hub/util/path.py
> Fixes bug with groups on hub cloud datasets

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
typo in bug_report.md, change "Pycharme" to "PyCharm"
> bug_report.md typo and README Badge fix

- .github/workflows/benchmark_pr.yml
minor bug fix for the benchmark code
minor bug fix for the benchmark code
> minor bug fix for the benchmark code

- hub/integrations/pytorch/common.py
- hub/integrations/tests/test_pytorch.py
Pytorch now works properly with text.
> Fixes pytorch with text

- .github/workflows/compare_benchmarks.yml
added bench repo branch input, set units as default
added bench repo branch input, set units as default
> added bench repo branch input, set units as default

- hub/api/tests/test_api.py
- hub/util/casting.py
```python
ds = hub.empty("mem://test")
ds.create_tensor("labels", htype='class_label')
ds.labels.append(np.zeros((0,4), dtype = 'uint64'))  #  Fails
```
https://activeloop.atlassian.net/browse/AL-1312
> Autocast empty samples

- hub/api/tests/test_api.py
- hub/core/chunk_engine.py
Fix error when extending with empty list.
> [AL-1418] Fix error when extending with empty list

- hub/core/compression.py
Remove line probably added for debugging/validation
> Image compression: don't decompress while compressing 

- hub/core/dataset/hub_cloud_dataset.py
Add visualizer link  when loading hub datasets
https://activeloop.atlassian.net/browse/AL-1591
> [AL-1591] Add visualizer link when loading hub datasets

- README.md
removed hacktoberfest banner
removed hacktoberfest banner
> removed hacktoberfest banner

- hub/core/chunk/base_chunk.py
- hub/core/chunk/chunk_compressed_chunk.py
- hub/core/chunk/sample_compressed_chunk.py
- hub/core/chunk/test_chunk_compressed.py
- hub/core/chunk/test_sample_compressed.py
- hub/core/chunk/test_uncompressed.py
- hub/core/chunk/uncompressed_chunk.py
- hub/core/chunk_engine.py
- hub/core/meta/encode/tile.py
- hub/core/serialize.py
- hub/core/test_serialize.py
- hub/core/tiling/deserialize.py
- hub/core/tiling/optimizer.py
- hub/core/tiling/sample_tiles.py
- hub/core/tiling/serialize.py
- hub/core/tiling/test_optimizer.py
- hub/core/tiling/test_serialize.py
- hub/core/tiling/util.py
- hub/util/compression.py
> Mypy fixes

- README.md
> Add pytorch training example to readme

- hub/core/query/filter.py
- hub/core/query/query.py
- hub/core/query/test/test_query.py
Recreated from https://github.com/activeloopai/Hub/pull/1378
> Query to cache whole numpy array if it is data-cachable

- README.md
> Updated pytorch portion of readme

- hub/core/dataset/dataset.py
- hub/core/storage/gcs.py
- hub/core/storage/s3.py
> [AL-1519] Fix read only issue after pickling dataset/storage provider

- hub/api/tests/test_api_tiling.py
- hub/core/dataset/dataset.py
- hub/core/storage/gcs.py
- hub/core/storage/s3.py
- hub/util/version_control.py
> Fix tiling + version control

- hub/core/compute/provider.py
- hub/core/compute/serial.py
- hub/core/tests/test_compute.py
- hub/core/transform/test_transform.py
- hub/core/transform/transform.py
- hub/util/transform.py
This implementation should be more stable than the previous one.
> [AL-1597] Use alternate implementation of progress bar for Hub compute

- hub/core/dataset/dataset.py
> Fix locking issue in fast query

- hub/core/transform/transform.py
> Make decorated functions work with filter

- hub/__init__.py
- hub/core/dataset/dataset.py
- hub/core/version_control/test_version_control.py
- hub/util/exceptions.py
- hub/util/version_control.py
https://activeloop.atlassian.net/browse/AL-1631
> [AL-1631] Commit with custom hash

- hub/core/dataset/dataset.py
> Fix windows pickling issue

- hub/requirements/common.txt
Unpin numcodecs and pillow version
> Unpin numcodecs and pillow version

- hub/core/chunk/chunk_compressed_chunk.py
- hub/core/transform/test_transform.py
- hub/util/transform.py
> Fixes overflow due to CompressedChunks leading to errors in transformed datasets

- hub/core/storage/s3.py
> [AL-1685] Add retry for incomplete read error

- hub/core/dataset/dataset.py
- hub/core/version_control/test_version_control.py
- hub/util/diff.py
- Makes the diff message more easy to understand
> [AL-1639] Clarify diff message

- README.md
FFmpeg acknowledgement
Acknowledge the FFmpeg team
> FFmpeg acknowledgement

- hub/api/tests/test_api.py
- hub/core/storage/local.py
Update test_persist_keys to cover windows case
> Fix local provider keys on windows

- hub/compression.py
> Fixing jpeg2000 dosctring in compressions

- hub/api/tests/test_api.py
> Enable remote video url test

- hub/api/tests/test_api.py
- hub/core/chunk_engine.py
- hub/core/index/index.py
- hub/core/index/tests/test_index.py
> [AL-1699][AL-1700] Fix indexing issues

- hub/core/query/filter.py
> Dataset view saving: small fix for #plat

- hub/integrations/pytorch/common.py
- hub/integrations/tests/test_pytorch.py
> [Small bug fix] Pytorch + transform dict bug

- hub/core/chunk_engine.py
> [Bug fix] Removes repeated key misses for CommitChunkSet in some old datasets

- README.md
Remove ffmpeg acknowledgement as we use them via pyav dependency, i.e we dont have any headers / sources copied as such.
> Remove ffmpeg ack

- hub/api/read.py
> [AL-1711] API documentation

- hub/util/keys.py
> [Tiny] Change dataset diff path

- README.md
> Revert "Updated formatting of features in readme"

- hub/core/dataset/dataset.py
> Quick fix for plat: remove is_sequence check

- hub/core/dataset/dataset.py
> [API Docs] Fixes shuffle link

- hub/core/query/query.py
- hub/core/query/test/test_query.py
> [AL-1718] - Do not throw exception if there is NameException in ds.filter

- hub/client/client.py
> Retry backend requests on failure

- .github/workflows/test-pr-on-label.yml
- .github/workflows/test-push.yml
> Add google drive refresh token to workflow

- hub/api/tests/test_text.py
- hub/core/meta/encode/base_encoder.py
- hub/core/meta/encode/tests/test_byte_positions_encoder.py
> [AL-1746] Fix encoder updates

- hub/core/dataset/dataset.py
- hub/core/dataset/hub_cloud_dataset.py
- hub/visualizer/visualizer.py
Track ds.visualize with bugout
Open hub cloud datasets directly in visualizer without local server
Support for hub cloud datasets visualization in Google Colab
Support for different visualizer backends (prod, dev, local).
> Next iteration for ds.visualize

- hub/core/dataset/dataset.py
> [AL-1741] Suppress loading messages on dataset deserialization

- hub/api/tests/test_api.py
- hub/util/version_control.py
> [AL-1752] Version control + Sequences fix

- hub/util/transform.py
> Reduces warning on copying datasets

- hub/core/transform/test_transform.py
- hub/util/encoder.py
- hub/util/transform.py
> [AL-1744] Sequence + transform fix

- bin/Dockerfile
- bin/Dockerfile.dev
- bin/docker-compose.yaml
- hub/api/tests/test_api_with_compression.py
- hub/api/tests/test_sample_info.py
* clean up miniaudio from tests
* update docker
> docker update, rm miniaudio

- hub/api/tests/test_insertion_out_of_order.py
- hub/core/chunk_engine.py
- hub/core/tensor.py
> Fixes linked tensors + random assignment

- hub/core/index/index.py
> [AL-1743] Improve DynamicTensorNumpyError message for sequence tensors

- hub/core/storage/google_drive.py
- setup.py
> [AL-1759] Fix google drive import error when importing hub

- hub/api/dataset.py
- hub/core/dataset/dataset.py
Add reporting for following:
diff, log, merge, create_group, copy, deep_copy
> [AL-1754] Add reporting for missing features

- hub/core/storage/google_drive.py
- hub/core/tensor.py
- hub/core/transform/test_transform.py
- hub/util/encoder.py
- setup.py
Fixes: #1629 
Fixes following issues:
* On creating a tensor without specifying any htype, it has a default htype of None, and on appending a sample it gets the generic htype. But if you run a transform instead of appending, the htype remains None.
* Creating a sequence htype tensor return a link[sequence[...]] htype instead of sequence[...]
> [AL-1760][AL-1761] Htype fixes

- hub/api/tests/test_api.py
- hub/core/dataset/dataset.py
- hub/core/meta/dataset_meta.py
- hub/core/version_control/test_version_control.py
Added functionality to rename groups.
> [AL-1625] Rename groups

- hub/api/dataset.py
- hub/core/dataset/dataset.py
- hub/core/fast_forwarding.py
>  Tensor meta fast forwarding + rename ds.copy creds arg

- hub/api/tests/test_api.py
- hub/core/chunk_engine.py
- hub/core/tensor.py
> [BUG] Delete sequence encoder when tensor is cleared

- hub/core/query/filter.py
- hub/core/query/query.py
- hub/core/query/test/test_query.py
> [AL-1762] Fix multiple chunks case in queries

- hub/api/tests/test_api.py
- hub/core/meta/dataset_meta.py
> Fixes group deletion issues

- conftest.py
- hub/client/client.py
- hub/client/config.py
- hub/tests/client_fixtures.py
> Run hub tests in staging.

- hub/core/io.py
- hub/integrations/tests/test_pytorch.py
- hub/util/dataset.py
> Fix tensor renames for ds.pytorch

- hub/api/tiled.py
> [AL-1765] Docstring for hub.tiled

- hub/api/tests/test_link.py
- hub/core/dataset/dataset.py
> [AL-1779] Adds get_creds method for link credentials

- hub/api/tests/test_api_tiling.py
- hub/core/chunk/chunk_compressed_chunk.py
- hub/core/tiling/sample_tiles.py
> [AL-1784] Tiling bug fix

- hub/core/tensor.py
> [AL-1745] .data() returns numpy arrays as list

- hub/core/query/test/test_query.py
> Reduce arg combinations for query test (Make CI faster)

- hub/api/tests/test_rechunk.py
- hub/core/chunk_engine.py
> Fixes rechunking keyerror

- hub/core/lock.py
- hub/core/storage/lru_cache.py
- hub/core/storage/tests/test_storage_provider.py
- hub/util/version_control.py
> Fix flush order

- hub/core/dataset/hub_cloud_dataset.py
> [AL-1645] Prevent printing visualization message in transforms

- hub/core/meta/encode/base_encoder.py
- hub/core/meta/encode/tests/test_shape_encoder.py
> Encoder fixes

- hub/integrations/pytorch/dataset.py
- hub/integrations/pytorch/pytorch.py
- hub/integrations/pytorch/shuffle_buffer.py
- hub/integrations/tests/test_pytorch.py
- hub/integrations/tests/test_pytorch_dataloader.py
> Fix pytorch shuffle slowdown

- hub/api/tests/test_api.py
> Fixed windows failing tests

- hub/core/dataset/dataset.py
Fixes a code path which is not reached in the testing environment.
> Fix get_views()

- hub/core/query/test/test_query.py
Remove tk that cause tests to fail
> remove tk from tests

- hub/core/tensor.py
Added docstring for `tensor.timestamp`
> Docstring for timestamp

- hub/util/transform.py
> [AL-1800] Transforms should respect tiling threshold

- hub/api/tests/test_api.py
- hub/core/partial_reader.py
- hub/core/storage/s3.py
Partial reading of empty sample was causing the entire chunk to be loaded and an incorrect buffer was being returned.
> [BUG] Fix empty sample partial read

- hub/api/tests/test_api.py
- hub/core/chunk_engine.py
Enables appending to `class_label` tensors with text. Automatically updates `tensor.info.class_names`.
> [AL-1787] Enable appending to class_label tensors with text

- hub/core/io.py
> spell check - Found pytorch misspelt while reading docs

- hub/api/tests/test_video.py
- hub/core/tensor.py
Support accessing timestamps for linked videos
> Support timestamps for linked videos

- hub/core/dataset/dataset.py
- hub/core/dataset/view_entry.py
- hub/integrations/pytorch/shuffle_buffer.py
If a view is a sub dataset, then it should inherit credentials from its parent.
> [AL-1823] Make sure credentials are managed properly when loading nested datasets

- hub/core/dataset/dataset.py
- hub/core/dataset/view_entry.py
- hub/core/query/test/test_query.py
`ds.get_view(id)` returns ViewEntry for a specific view stored in the dataset  (or user account for hub datasets) using view id.
```
ds = hub.load(path)
view = ds[1:99]
view.save_view(id="abcd")
ds = hub.load(path)
view = ds.get_view("abcd").load()
```
> [AL-1821] ds.get_view

- hub/api/dataset.py
- hub/core/dataset/hub_cloud_dataset.py
Register hub datasets created by deepcopy on the backend
> [AL-1822] Register hub datasets created by deepcopy

- hub/client/log.py
Prevent importing hub from changing logging configuration
Closes #1727
> Prevent changing logging configuration

- hub/api/tests/test_video.py
- hub/visualizer/tests/test_playback.py
Fix passing creds to linked video tensors in tests.
> Fix linked video tests

- hub/api/tests/test_api.py
- hub/util/path.py
> [AL-1780] [Small] Add support for pathlib.Path arguments 

- hub/api/tests/test_info.py
- hub/util/version_control.py
> Fixes a bug with Version control + Info modification

- hub/api/tests/test_api.py
- hub/core/chunk_engine.py
Allow updation of class_label samples with text
> Update class_labels with text

- hub/api/tests/test_insertion_out_of_order.py
> Removes sequence test

- hub/api/tests/test_video.py
- hub/core/tensor.py
- Fix test
- Rename `timestamp` property to `timestamps`
> [BUGFIX] Make linked video test work without google creds

- hub/core/dataset/dataset.py
- hub/core/dataset/hub_cloud_dataset.py
> [API] Added example for changing credential management

- hub/core/dataset/dataset.py
- hub/core/dataset/view_entry.py
> Allow platform to specify username for saving queries against public datasets

- hub/core/dataset/dataset.py
- hub/core/dataset/view_entry.py
> [AL-1817][AL-1842] API reference for ViewEntry class

- hub/core/storage/s3.py
> [Improvement] Retries in s3 get_object_from_full_url

- hub/core/dataset/dataset.py
- hub/core/dataset/view_entry.py
- hub/core/index/index.py
- hub/core/query/test/test_query.py
- hub/core/tensor.py
- hub/requirements/common.txt
- hub/util/invalid_view_op.py
- hub/util/storage.py
> [AL-1851][AL-1852][AL-1853][AL-1854] Allow plat to provide creds explicitly while saving views to user dir

- hub/api/tests/test_link.py
- hub/core/transform/transform_tensor.py
> [Bug] Fixes bug with links and compute

- hub/core/dataset/dataset.py
> Allow passing creds explicitly for external views

- hub/core/dataset/dataset.py
- hub/core/dataset/view_entry.py
> Enable parallelization for view optimization

- hub/integrations/pytorch/shuffle_buffer.py
> Make pbar on shuffle buffer filling readable

- hub/api/tests/test_api.py
- hub/api/tests/test_dicom.py
- hub/api/tests/test_json.py
- hub/api/tests/test_text.py
- hub/core/tensor.py
> [AL-1809] refactor .data

- hub/__init__.py
> Unhide auto and util submodules in docs

- hub/core/dataset/dataset.py
- hub/core/dataset/hub_cloud_dataset.py
- hub/core/dataset/view_entry.py
- hub/util/logging.py
> Fix visualizer links for local views

- hub/api/dataset.py
- hub/api/tests/test_api.py
- hub/client/client.py
- hub/core/dataset/dataset.py
- hub/tests/client_fixtures.py
- hub/util/bugout_reporter.py
> [DL-593] Bugout correctly identifying the user's username when tokens are used

- hub/core/dataset/dataset.py
> [DL-620] Prevent saving of dataset views for public datasets when user is not logged in

- hub/core/storage/s3.py
> [DL-590] S3: Always show retry warnings

- hub/tests/path_fixtures.py
Use reuploaded dataset for video streaming test.
> Use reuploaded dataset for video test

- hub/__init__.py
- hub/api/tests/test_agreement.py
- hub/client/client.py
- hub/client/config.py
- hub/client/utils.py
- hub/constants.py
- hub/core/compute/ray.py
- hub/core/dataset/hub_cloud_dataset.py
- hub/requirements/plugins.txt
- hub/util/agreement.py
- hub/util/bugout_reporter.py
- hub/util/exceptions.py
- hub/util/storage.py
Agreements are now handled in the backend instead of locally keeping track of accepted agreements.
Unit tests will fail for agreements till agreements PR in the backend is merged to staging
> [AL-1848] New agreements handling

- hub/core/dataset/dataset.py
- hub/core/version_control/test_version_control.py
- hub/util/version_control.py
Newly created or deleted tensors in the head commit weren't being properly accounted for in ds.reset, this PR fixes it.
> [AL-1884] Fixes bug with ds.reset for newly added/deleted tensors

- hub/core/chunk_engine.py
- hub/core/transform/test_transform.py
- Text, json, list and links were not being handled correctly during rechunking. This fix temporarily disables rechunking for these data types, till we have a better fix.
- There was another issue where global index in pop wasn't being translated to local chunk index, this has also been fixed.
> [Bug] Fixes issue with pop + rechunking

- hub/__init__.py
> Update hub version

- hub/util/bugout_reporter.py
This is a potential fix to this issue. It is based on this PR: https://github.com/activeloopai/Hub/pull/1800
> Older reporting configurations were not properly handling username

- hub/api/tests/test_none.py
- hub/core/chunk/base_chunk.py
- hub/core/chunk_engine.py
- hub/util/empty_sample.py
- Empty lists now have the same behaviour as using None during appends and updates
> [AL-1858] Treat empty list as None

- hub/api/tests/test_rechunk.py
- hub/core/chunk/base_chunk.py
- hub/core/chunk_engine.py
- hub/core/sample.py
- hub/core/serialize.py
> [AL-1888] Enable rechunking for text like htypes

- hub/__init__.py
> Update version to 2.7.5

- hub/api/dataset.py
- hub/util/exceptions.py
Changed the message displayed by TokenPermissionError.
> [AL]-1813-Small Fix

- hub/util/class_label.py
Enabled progress bar for syncing labels.
> Enable progressbar for syncing labels

- hub/api/tests/test_rechunk.py
- hub/core/chunk_engine.py
- hub/core/linked_chunk_engine.py
> [Bugfix] Fixes rechunking with hub link + cloud paths

- hub/__init__.py
> Update version after release

- hub/constants.py
- hub/core/dataset/dataset.py
- hub/hooks.py
- hub/integrations/wandb/wandb.py
- hub/util/version_control.py
> Wandb integration data lineage updates + refac

- hub/visualizer/visualizer.py
> Use staging visualizer in tests. Correct dev visualizer url.

- .github/workflows/benchmark_pr.yml
> Temp Disabled Hub Benchmark

- hub/util/class_label.py
> Avoid printing syncing labels message when no labels were added

- hub/__init__.py
> Change main version after release

- hub/__init__.py
> Update version to 2.8.2

- hub/api/tests/test_api.py
- hub/core/dataset/dataset.py
Added ability to compute min and max length for dataset
> [DL-655] Added min and max length options

- hub/experimental/convert_to_hub3.py
- hub/experimental/dataloader.py
- hub/experimental/test_pytorch.py
- hub/requirements/common.txt
> Ds speedup

- README.md
- docs/source/conf.py
- Update docs URL in readme
- Get docs version from hub's __init__
> Update docs URL in readme

- hub/experimental/dataloader.py
- hub/experimental/test_pytorch.py
- hub/integrations/wandb/wandb.py
> Local wandb

- hub/__init__.py
> Update init version to 2.8.4

- hub/experimental/dataloader.py
- hub/experimental/hub3_query.py
> more adjustments on docstrings

- hub/experimental/convert_to_hub3.py
- hub/experimental/dataloader.py
- hub/util/dataset.py
> Big speedup for experimental dataloader initialization

- hub/core/dataset/dataset.py
Removed unnecessary imports that are no longer used, one of them is iterable, that causes issues on python 3.10
> [BUGFIX] Fix imports

- hub/__init__.py
> Update version to 2.8.5

- hub/api/dataset.py
> [DL-710] Fix locking issue with deepcopy

- hub/experimental/convert_to_hub3.py
- hub/experimental/dataloader.py
- hub/experimental/util.py
> Improve indra error message in case of missing dependencies

- hub/experimental/dataloader.py
- hub/experimental/hub3_query.py
> add docstrings

- hub/integrations/wandb/wandb.py
> [DL-715] Fix wandb integration path issue

- hub/core/transform/test_transform.py
- hub/core/transform/transform_tensor.py
- hub/util/transform.py
Resolved memory leak issue associated with hub.compute
> [DL-645] Fix memory leak in transforms

- hub/api/tests/test_api.py
- hub/core/dataset/dataset.py
- hub/core/index/__init__.py
- hub/core/index/index.py
- hub/core/tensor.py
Fixes: #1877 
Add numpy like indexing by ellipsis for tensors.
> [DL-714] Add Ellipsis support for indexing

- hub/core/fast_forwarding.py
> Fixes bug with is_sequence

- hub/core/dataset/dataset.py
- hub/core/dataset/hub_cloud_dataset.py
- hub/core/query/test/test_query.py
- hub/core/storage/provider.py
Allow view optimization when read_only=True by fetching write access creds on the fly.
> [DL-711] Allow view optimization when read_only=True

- hub/__init__.py
> Update version to 2.8.6

- hub/experimental/dataloader.py
> Indra import fix

- docs/source/Tensor-Query-Language.rst
- docs/source/hub.experimental.dataloader.rst
- docs/source/index.rst
- hub/experimental/__init__.py
- hub/experimental/dataloader.py
- hub/experimental/hub3_query.py
Documentation for Tensor Query Language
> Tensor Query Language documentation

- hub/util/storage.py
> Passing token down

- deeplake/api/tests/test_link.py
- deeplake/core/dataset/dataset.py
- deeplake/core/link_creds.py
- deeplake/core/linked_chunk_engine.py
Removed warning saying that for link[image], sample_compression is not valid and also removed print message when you specify credentials
> [Bugfix] Removing unnecessary warning and print messages

- deeplake/__init__.py
> Staging 3.0.5

- deeplake/api/tests/test_hosted_datasets.py
- deeplake/util/storage.py
> [AL-1967] Fixes issue with readonly mode error raised despite not trying to write to dataset

- deeplake/__init__.py
> Update staging deeplake version 

- deeplake/core/chunk_engine.py
- deeplake/core/dataset/dataset.py
- deeplake/core/storage/lru_cache.py
- deeplake/core/tensor.py
`fetch_chunks=True` when iterating
```python
import deeplake as dp
import tqdm
ds = dp.load('hub://activeloop/mnist-train')
for sample in tqdm.tqdm(ds):
sample["images"].numpy()
```
Before: ~2h, After: <20s
Heuristic to detect range iteration:
```python
import deeplake as dp
import tqdm
ds = dp.load('hub://activeloop/mnist-train')
for i in tqdm.tqdm(range(len(ds))):
ds[i]["images"].numpy()
```
Before: ~2h, After: 25s
> [DL-718] Fast iteration

- deeplake/integrations/wandb/wandb.py
> [DL-754] Add reporting for W&B integration

- setup.py
> Update libdeeplake version

- deeplake/__init__.py
> Update Deep Lake version after release

- README.zh-cn.md
- deeplake/api/tests/test_api.py
- deeplake/core/dataset/dataset.py
- deeplake/core/tensor.py
1 - Allows pandas like column-wise views:
```python
import deeplake as dp
ds = dp.empty("mem://test")
with ds:
ds.create_tensor("x")
ds.create_tensor("y")
ds.create_tensor("z")
#----append data-----#
view = ds[["x", "z"]]
assert list(view.tensors) == ["x", "z"]
```
2 - Adds `ds.min_view` and `ds.max_view`
> [DL-701] Columnar views

- deeplake/api/tests/test_polygons.py
- deeplake/core/polygon.py
Fix bug when appending polygons as numpy array + test.
> [DL-777] Polygons bug fix

- deeplake/api/info.py
- deeplake/api/tests/test_api.py
- deeplake/requirements/tests.txt
Fix compatibility issue with rich : https://hubdb.slack.com/archives/C01D9P7SSKU/p1664902127126619
> [DL-783] Rich compatibility

- deeplake/core/dataset/dataset.py
- deeplake/experimental/dataloader.py
- deeplake/experimental/test_pytorch.py
- deeplake/integrations/tests/test_pytorch.py
Allow specifying transform kwargs in ds.pytorch call.
> [DL-755] Specify transform kwargs in ds.pytorch call

- docs/source/Htypes.rst
- docs/source/Installation.rst
- docs/source/_static/csv/installation.csv
- Added managed creds info to Htypes page
- Update Installation page
> [DL-764] API reference updates

- deeplake/api/dataset.py
> [DL-730] Make sure hub.list does not report the token to bugout

- setup.py
Lib Deep Lake upgrade to 0.0.20
- Query shape(image)  bug fixed
- Query regex for contains  function deployed. Example: SELECT * WHERE contains(labels, '*an*')  on imagenet, will return all samples with class names containing an . There are two wildcards supported *  - any number of characters (including 0) and ? - exactly one character.
> libdeeplake upgrade

- deeplake/core/chunk_engine.py
> Fix partial read skip for chunk compressed chunks

- deeplake/core/dataset/dataset.py
- deeplake/core/tensor.py
Ignore tensors for which tensor meta is written to storage but dataset meta not updated.
https://hubdb.slack.com/archives/C01D9P7SSKU/p1663355561201769
> [DL-726][DL-789] Ignore corrupt tensors + fetch_chunks for .data(), .text() etc

- deeplake/visualizer/tests/test_visualizer.py
> Fix visualizer test

- deeplake/experimental/dataloader.py
- deeplake/visualizer/tests/test_visualizer.py
> [AL-1990] add shuffle argument to .shuffle

- deeplake/core/dataset/deeplake_cloud_dataset.py
- deeplake/core/link_creds.py
Add verbosity arg to fetching creds
> [DL-756] Log loading creds except in transforms

- deeplake/api/tests/test_polygons.py
- deeplake/core/chunk/uncompressed_chunk.py
> [CUS-24] Fix polygons bug with fixed shape inputs

- README.md
- deeplake/core/io.py
- deeplake/integrations/pytorch/dataset.py
- deeplake/integrations/tests/test_pytorch.py
* Bug in pytorch dataloader with dataset views with continuous indices and shuffle=True
* Fix bug with indexing and pytorch: https://app.slack.com/client/TMD3FUVR8/C01LWP7CW69
* Fix memory issue with shuffling: https://hubdb.slack.com/archives/C01LWP7CW69/p1665725602922619
> [DL-814][CUS-14][CUS-17] Pytorch fixes

- deeplake/core/dataset/dataset.py
> [DL-821] Fix allowing commit on views

- deeplake/api/tests/test_polygons.py
- deeplake/core/chunk_engine.py
Disabled caching for fixed shape polygons
> Fixed shape polygon fix

- deeplake/experimental/convert_to_libdeeplake.py
- deeplake/experimental/util.py
- setup.py
> Remove tiling extraction

- deeplake/experimental/dataloader.py
- deeplake/integrations/pytorch/common.py
- deeplake/integrations/pytorch/pytorch.py
- Will require libdeeplake update
> Improves experimental dataloader performance for tensors with jpeg and png images

- deeplake/experimental/convert_to_libdeeplake.py
- deeplake/experimental/util.py
> fixed merge conflict

- deeplake/__init__.py
> Update deeplake version after release

- deeplake/integrations/pytorch/shuffle_buffer.py
> Update shuffle buffer to handle bytes

- deeplake/api/tests/test_link.py
- deeplake/core/chunk_engine.py
- deeplake/core/linked_chunk_engine.py
- deeplake/core/tensor.py
> [AL-1964] Expose path for linked tensors

- bin/publish_pip.sh
> No Wheels (fix for pip install on Windows)

- deeplake/core/chunk_engine.py
- deeplake/core/linked_chunk_engine.py
> [AL-2010] Fixes verification of linked samples during rechunking

- docs/source/Htypes.rst
- docs/source/_static/csv/htypes.csv
Added docs for mesh and point_cloud types
> Mesh & Point Cloud htype's docs

- deeplake/core/storage/s3.py
> [AL-1992] [CUS-18] Fixes token expiration issue using hub:// datasets

- deeplake/api/dataset.py
- deeplake/api/tests/test_access_method.py
- deeplake/api/tests/test_api.py
- deeplake/util/access_method.py
- deeplake/util/storage.py
- Local downloads dataset if it doesn't already exist
- Download overwrites existing dataset
- Closes #1952
> [DL-879] Improve download API

- deeplake/__init__.py
- setup.py
> promote libdeeplake version to 0.0.25

- deeplake/api/tests/test_json.py
- deeplake/util/json.py
> [CUS-30] Add support for bytes in json tensors

- deeplake/util/check_latest_version.py
> Add timeout to Pypi version check

- deeplake/__init__.py
- deeplake/experimental/test_pytorch.py
- setup.py
> Bump libdeeplake version, fix windows test

- setup.py
> [AL-2024] Add MPL license to Deep Lake in Pypi

- deeplake/core/dataset/dataset.py
- deeplake/experimental/dataloader.py
- deeplake/experimental/libdeeplake_query.py
- deeplake/experimental/test_query.py
> Allow np.array as sampler weights. Update docs.

- deeplake/core/dataset/dataset.py
- deeplake/core/transform/__init__.py
- deeplake/core/transform/transform.py
- deeplake/enterprise/dataloader.py
- docs/source/Dataloader.rst
- docs/source/Datasets.rst
- docs/source/Htypes.rst
- docs/source/Sampler.rst
- docs/source/Tensor-Query-Language.rst
- docs/source/Utility-Functions.rst
- docs/source/deeplake.core.transform.rst
- docs/source/deeplake.enterprise.rst
- docs/source/index.rst
- API reference for enterprise features
- Docstring fixes
> [DL-895] Enterprise API reference

- deeplake/enterprise/dataloader.py
> Dataloader len fix

- deeplake/integrations/tf/datasettotensorflow.py
- Stop iteration warnings when iterating over tf dataset
> [DL-910] Tensorflow iteration fix

- deeplake/core/dataset/dataset.py
- deeplake/enterprise/dataloader.py
- deeplake/experimental/dataloader.py
- deeplake/experimental/util.py
> Handle repeated samples in shuffle

- deeplake/core/dataset/dataset.py
- deeplake/enterprise/dataloader.py
- deeplake/integrations/mmdet/__init__.py
- deeplake/integrations/mmdet/mmdet_.py
- deeplake/integrations/mmdet/mmdet_utils.py
- deeplake/integrations/pytorch/pytorch.py
- deeplake/integrations/pytorch/shuffle_buffer.py
- deeplake/integrations/tests/test_mmdet.py
- deeplake/requirements/plugins.txt
- deeplake/tests/path_fixtures.py
Added support for MMDet object detection integration
> Mmdet latest changes

- deeplake/api/dataset.py
- deeplake/auto/tests/test_kaggle.py
- deeplake/auto/unstructured/base.py
- deeplake/auto/unstructured/image_classification.py
- deeplake/core/dataset/dataset.py
- deeplake/enterprise/dataloader.py
> [DL-905] [DL-916] Consistent progressbar arg + example for decode_method

- deeplake/integrations/mmdet/mmdet_.py
- deeplake/integrations/mmdet/mmdet_utils.py
- deeplake/integrations/tests/test_mmdet.py
Added support for:
1. YOLOXHSVRandomAug 
2. RandomCrop
3. RandomCenterCropPad
4. MinIoURandomCrop
> MMDet Augmentations Fix

- deeplake/enterprise/dataloader.py
> [DL-793][CUS-46] Add wandb logging to indra loader

- deeplake/core/dataset/dataset.py
Resolves the issue with main, that requires torch to be installed
> Fixing main

- deeplake/integrations/pytorch/pytorch.py
> [AL-2037] Print error that sequences are not allowed with the pytorch dataloader

- deeplake/core/dataset/dataset.py
- Fixes a bug with rechunk and labels tensor
- Speeds up rechunking
> [AL-2054] Rechunk bug fix and speedup

- deeplake/auto/unstructured/image_classification.py
- deeplake/util/object_3d/object_base_3d.py
- deeplake/util/object_3d/point_cloud.py
> Remove pandas imports

- deeplake/api/tests/test_pop.py
- deeplake/auto/unstructured/image_classification.py
- deeplake/core/chunk_engine.py
- deeplake/core/meta/encode/tile.py
- deeplake/util/object_3d/object_base_3d.py
- deeplake/util/object_3d/point_cloud.py
> [AL-2045] Fix corruption caused by pop

- deeplake/core/dataset/dataset.py
> [Bug Fix] Pickling fix for DDP + Enterprise loader

- deeplake/integrations/mmdet/mmdet_.py
- deeplake/integrations/mmdet/mmdet_utils.py
- deeplake/integrations/tests/test_mmdet.py
> [CUS-50] MMdet Mask Fix

- .github/workflows/test-push.yml
- deeplake/integrations/tests/test_mmdet.py
> mmdet_test_fix

- deeplake/api/tests/test_api.py
- deeplake/core/dataset/dataset.py
- deeplake/util/scheduling.py
- docs/source/Random-Split.rst
- docs/source/index.rst
> [AL-2078] Switch random split doc section

- deeplake/api/tests/test_api.py
- deeplake/api/tests/test_link.py
- deeplake/core/tensor.py
- deeplake/core/tensor_link.py
- deeplake/core/tests/test_io.py
- deeplake/core/transform/transform_tensor.py
- deeplake/util/object_3d/ply_readers.py
- deeplake/util/testing.py
> Tests fix (py3.8)

- deeplake/enterprise/__init__.py
- deeplake/enterprise/dataloader.py
- deeplake/enterprise/util.py
> remove torch dependency

- deeplake/visualizer/visualizer.py
> Print hint to forward the visualizer port.

- deeplake/__init__.py
> Update Deep Lake version before release

- deeplake/api/dataset.py
- docs/source/Datasets.rst
- docs/source/deeplake.api.dataset.rst
- docs/source/deeplake.rst
Added ``ingest_coco`` method to docs in relevant places.
> Added ingest_coco to docs

- deeplake/enterprise/dataloader.py
> [CUS-64] Enterprise dataloader support kwargs, fixes issue with pytorch lightning

- deeplake/api/tests/test_api.py
- deeplake/util/scheduling.py
> Fix Random split + views issue

- deeplake/util/object_3d/ply_readers.py
> Removed pandas dependency

- deeplake/enterprise/__init__.py
- deeplake/enterprise/dataloader.py
- deeplake/enterprise/test_tensorflow.py
- deeplake/enterprise/util.py
- deeplake/integrations/pytorch/common.py
- deeplake/integrations/pytorch/shuffle_buffer.py
- deeplake/integrations/tf/common.py
Supports all the same features as .pytorch with the exception of distributed=True
> [AL-2069] Adds tensorflow support to enterprise dataloader

- deeplake/enterprise/dataloader.py
> Removed Shuffling Exception

- deeplake/core/compression.py
- deeplake/core/serialize.py
- docs/source/_static/csv/installation.csv
- setup.py
> Disable tiling for NIFTI

- deeplake/core/chunk/base_chunk.py
- deeplake/core/transform/test_transform.py
- deeplake/util/encoder.py
> [DL-943] Nones + transform fix

- deeplake/core/chunk_engine.py
Fixes #2089
Fix Json and other text like tensors being treated as fixed shape.
> Json fixed shape issue

- deeplake/api/tests/test_api.py
- deeplake/core/dataset/dataset.py
- deeplake/core/transform/transform.py
> Fix deletion of temp tensors in read_only mode

- deeplake/core/sample.py
- deeplake/util/json.py
> Update NIFTI sample info

- deeplake/core/chunk_engine.py
> Link progress bar fix

- deeplake/core/chunk/base_chunk.py
> [AL-2087] Better error handling when forgetting deeplake.read when appending data

- deeplake/core/dataset/dataset.py
- deeplake/enterprise/dataloader.py
- deeplake/integrations/mmdet/mmdet_.py
- deeplake/integrations/pytorch/dataset.py
- deeplake/integrations/pytorch/pytorch.py
- deeplake/integrations/tests/test_mmdet.py
> Various mmdet fixes

- deeplake/api/tests/test_link.py
- deeplake/core/chunk/base_chunk.py
- deeplake/core/chunk_engine.py
- deeplake/core/tensor.py
- deeplake/core/tensor_link.py
> [AL-2098] Fix min/max shape for linked tensors

- deeplake/api/dataset.py
- deeplake/auto/tests/test_yolo_template.py
- deeplake/auto/unstructured/yolo/utils.py
- deeplake/auto/unstructured/yolo/yolo.py
- docs/source/Datasets.rst
- docs/source/deeplake.api.dataset.rst
- docs/source/deeplake.rst
> Slight fixes to ingest_yolo and ingest_coco

- deeplake/__init__.py
> Update version for release

- deeplake/__init__.py
> Bump version to 3.2.1 for release

- deeplake/__init__.py
> Bump version

- deeplake/integrations/pytorch/shuffle_buffer.py
> Pytorch DDP fix

- deeplake/constants.py
- deeplake/core/chunk_engine.py
- deeplake/core/storage/lru_cache.py
- deeplake/core/version_control/commit_chunk_map.py
- deeplake/core/version_control/commit_chunk_set.py
- deeplake/util/copy.py
- deeplake/util/keys.py
> No copy merge

- deeplake/util/version_control.py
> Add error message for integrity check

- deeplake/api/tests/test_api.py
- deeplake/core/chunk_engine.py
- deeplake/core/tensor.py
- Fix bug with tobytes for sequences
> [AL-2096] Fix tobytes for sequences

- deeplake/api/tests/test_polygons.py
- deeplake/core/chunk/chunk_compressed_chunk.py
- deeplake/core/chunk/sample_compressed_chunk.py
- deeplake/core/chunk/uncompressed_chunk.py
- deeplake/core/transform/transform_tensor.py
- Fix memory leak in polygons that prevented addition of new samples into the tensor
- Fix chunk compression issue for polygons that broke `tensor.numpy()`
> [BUGFIX] Fix bugs with polygons

- deeplake/visualizer/visualizer.py
> Fixed ds.visualize for ENV creds_key.

- deeplake/core/tensor_link.py
- Fixed extend slowdown when shape tensor is present.
> [AL-2118] Extend slowdown fix

- deeplake/core/chunk_engine.py
- deeplake/core/tensor.py
- `tensor.meta.name` can be None for older datasets created before rename functionality so need to fall back on `tensor.key` in such cases
> [BUGFIX] Fix None tensor name issue

- deeplake/core/transform/test_transform.py
- deeplake/core/transform/transform.py
- deeplake/core/transform/transform_tensor.py
> Fix class label behaviour in Deep Lake compute

- docs/source/Htypes.rst
- docs/source/_static/csv/htypes.csv
> [AL-2135] 3d bbox doc api

- deeplake/core/dataset/dataset.py
- deeplake/util/version_control.py
> [CUS-76] Better reset + rollback version control state in case of failed checkout

- deeplake/api/link.py
- deeplake/api/link_tiled.py
- deeplake/core/tensor_link.py
- deeplake/util/downsample.py
> Fixes to LinkTiled data

- deeplake/core/linked_chunk_engine.py
- deeplake/util/exceptions.py
- Better error messages in case of link verification fail
> [AL-2107] Improve link verification error handling

- deeplake/api/dataset.py
- deeplake/api/tests/test_grayscale.py
- deeplake/auto/tests/test_yolo_template.py
- deeplake/auto/unstructured/yolo/utils.py
- deeplake/auto/unstructured/yolo/yolo.py
- deeplake/core/chunk/chunk_compressed_chunk.py
- deeplake/core/chunk_engine.py
- deeplake/core/compression.py
- deeplake/core/fast_forwarding.py
- deeplake/core/io.py
- deeplake/core/meta/encode/chunk_id.py
- deeplake/core/query/filter.py
- deeplake/core/query/test/test_query.py
- deeplake/core/tensor.py
- deeplake/core/tensor_link.py
- deeplake/core/version_control/test_version_control.py
- deeplake/integrations/mmdet/mmdet_utils.py
- deeplake/integrations/pytorch/dataset.py
- deeplake/integrations/pytorch/pytorch.py
- deeplake/integrations/pytorch/shuffle_buffer.py
- deeplake/util/exceptions.py
- deeplake/util/tests/test_version_control.py
- Register correct sample shape for grayscale images in shape tensor if being appended to tensor having rgb samples.
> [AL-2117] Sample shape tensor fix for grayscale images

- .github/workflows/test-push.yml
- deeplake/integrations/mmdet/mmdet_.py
- deeplake/integrations/mmdet/mmdet_utils.py
- deeplake/integrations/tests/test_mmdet.py
1. Fixed problems with W&B
2. Some minor changes
> Mmdet updates

- deeplake/__init__.py
> Bump version after deeplake release

- deeplake/enterprise/dataloader.py
> Change batch sampler value when distributed = True

- deeplake/integrations/mmdet/mmdet_.py
> MMDet test mode fix

- deeplake/core/dataset/dataset.py
- deeplake/core/dataset/deeplake_cloud_dataset.py
Changes the error message for trying to connect a `DeepLakeCloudDataset` with `ds.connect`.
Moved the API call code up, so that error terminates the method before anything else is done.
> [DL-944] Changed error message for ds.connect

- deeplake/integrations/mmdet/mmdet_.py
> Remove batch sampler assignment in mmdet integration

- deeplake/api/tests/test_downsample.py
- deeplake/core/tensor_link.py
- deeplake/enterprise/dataloader.py
- deeplake/util/downsample.py
- deeplake/util/keys.py
> [AL-2178] Adds downsampling support for binary masks and fix groups downsampling

- deeplake/enterprise/dataloader.py
> Dataloader + sampler fix

- deeplake/api/tests/test_rechunk.py
- deeplake/core/chunk_engine.py
> Fix bug in rechunking logic

- deeplake/visualizer/visualizer.py
> Visualizer changes for new ENV creds.

- deeplake/core/storage/gcs.py
- deeplake/core/storage/s3.py
> Fix credential expiry when using queries

- deeplake/integrations/mmdet/mmdet_.py
> mmdet big datasets fix

- deeplake/api/dataset.py
- deeplake/api/tests/test_api.py
- deeplake/constants.py
- deeplake/core/dataset/dataset.py
- deeplake/core/version_control/test_version_control.py
- deeplake/util/spinner.py
- `@spinner` decorator for time consuming functions.
> [AL-2175] Generic spinner decorator for long functions

- deeplake/integrations/mmdet/mmdet_.py
> MMDet Distributed validation fix

- deeplake/__init__.py
- setup.py
> Update versions before release

- deeplake/integrations/mmdet/mmdet_.py
> Revert mmdet validation fix

- deeplake/api/tests/test_update_samples.py
- Fix update sample test that is randomly failing. Updated assertion because we convert gray images to 3D
> Fix update sample test

- deeplake/core/dataset/dataset.py
- deeplake/enterprise/convert_to_libdeeplake.py
> Update credentials before creating enterprise dataloader

- deeplake/api/tests/test_api.py
- deeplake/core/dataset/dataset.py
- Should not clear temp tensors in `__setstate__` because they would be used by another process
> [AL-2187] Fix transforms with processed scheduler

- deeplake/__init__.py
> Update Deep Lake version

- deeplake/integrations/mmdet/mmdet_.py
- deeplake/integrations/mmdet/mmdet_utils.py
Fixed MMDet distributed validation
> Mmdet validation fix

- deeplake/core/tensor_link.py
- deeplake/util/downsample.py
> [AL-2185] Return empty sample if downsampling fails due to any reason

- docs/source/Htypes.rst
> Updated intrinsics docstring

- deeplake/core/storage/lru_cache.py
> Disable async flush in case import fails

- setup.py
> Remove hub dependency

- deeplake/core/storage/lru_cache.py
> Fixed undefined ASYNC_INSTALLED error.

- deeplake/__init__.py
- deeplake/api/tests/test_link.py
- deeplake/core/dataset/deeplake_cloud_dataset.py
- setup.py
> bump libdeeplake version

- deeplake/core/storage/s3.py
- setup.py
> Token update

- deeplake/api/tests/test_api.py
- deeplake/compression.py
- deeplake/core/tests/test_compression.py
- deeplake/tests/path_fixtures.py
> Temporarily disable apng compression

- deeplake/integrations/wandb/wandb.py
> [AL-2176] Ignore wandb exceptions

- deeplake/util/transform.py
> [AL-2205] Fix accessing cache with transforms

- deeplake/api/tests/test_pop.py
- deeplake/core/tensor.py
- Update links correctly when popping from sequence tensor
- Flat links have to be popped multiple times
> [AL-2213] Fix popping from sequences

- deeplake/api/dataset.py
- deeplake/api/tests/test_api.py
- deeplake/api/tests/test_reset.py
- deeplake/core/dataset/dataset.py
- deeplake/core/version_control/test_version_control.py
- deeplake/util/access_method.py
- deeplake/util/exceptions.py
- deeplake/util/path.py
- deeplake/util/version_control.py
- docs/source/Utility-Functions.rst
- docs/source/deeplake.rst
- Load datasets to specific versions using `path@version` format.
- Perform integrity checks on load and checkout
- If HEAD is corrupted, pass `reset=True` to load and checkout to reset HEAD and load previous commit
> [AL-2179] Reset option for load and checkout

- docs/source/Tensor-Query-Language.rst
> Fixed bad link in docs

- deeplake/integrations/huggingface/huggingface.py
- deeplake/integrations/tests/test_huggingface.py
- deeplake/util/exceptions.py
- Fixed TensorAlreadyExists error message.
- Add low-hanging fruit improvement which includes [this user request](https://github.com/activeloopai/deeplake/pull/2250):
-- Ability to overwrite the dataset
-- Ability to connect the dataset
-- Ability to authenticate using tokens
> Updates to ingest_huggingface

- .github/workflows/benchmark.yaml
- .github/workflows/benchmark_manual.yaml
> update benchmarks timeout

- deeplake/util/bugout_reporter.py
> Added bugout blacklist

- deeplake/util/iterable_ordered_dict.py
> fix reference counting in dict

- deeplake/api/tests/test_link.py
- deeplake/core/dataset/dataset.py
- deeplake/core/dataset/deeplake_cloud_dataset.py
- deeplake/core/link_creds.py
- deeplake/core/linked_chunk_engine.py
- deeplake/core/tensor.py
- deeplake/util/link.py
- Adds method to retrieve managed creds keys to Dataset object
- Makes the output of get_creds_keys immutable
- Adds method to check creds_key used for a sample to Tensor object
- Adds warning instead of error if managed creds aren't found on platform
- Fixes some backwards compatibility issues
> Creds changes

- deeplake/util/bugout_reporter.py
Reverts activeloopai/deeplake#2196
> Revert "Added bugout blacklist"

- deeplake/util/transform.py
> Better rechunk logic post transform

- deeplake/core/tensor.py
- deeplake/core/tensor_link.py
> [AL-2186] Fix warning when extending with None

- deeplake/util/spinner.py
> Write spinner to stderr

- deeplake/api/tests/test_api.py
- deeplake/core/chunk_engine.py
- deeplake/core/dataset/dataset.py
- deeplake/core/tensor.py
- Fix `ds.summary()` for views
- Fixes for tensor shapes
> [AL-2235] [AL-2244] [AL-2245] Fix summary for views

- deeplake/__init__.py
> Update Deep Lake before release

- deeplake/enterprise/dataloader.py
- deeplake/enterprise/dummy_dataloader.py
> [AL-2238] Fix unexpected behaviour when islice is used on dataloader

- deeplake/core/storage/lru_cache.py
- deeplake/core/storage/provider.py
- deeplake/core/storage/s3.py
Even if  `asyncio` is available, `nest_asyncio.apply()` can fail under certain conditions.
> Fix issue with async upload in notebook environments

- deeplake/requirements/common.txt
> Fix hard dependency on aioboto3 10.4.0

- deeplake/api/dataset.py
- deeplake/api/tests/test_reset.py
- deeplake/constants.py
- deeplake/core/dataset/dataset.py
- deeplake/core/version_control/commit_node.py
- deeplake/core/version_control/test_merge.py
- deeplake/util/keys.py
- deeplake/util/testing.py
- deeplake/util/version_control.py
- Store commit level info as backup in case version control info gets corrupted / missing.
- `fix_vc` method for dataset to force rebuild version control info.
> [AL-2227] Commit level info

- deeplake/cli/auth.py
- deeplake/client/client.py
- deeplake/client/utils.py
- deeplake/util/bugout_reporter.py
Adding bugout reporting to cases where user logs in with a token of `ACTIVELOOP_TOKEN` env variable.
> Added reporting for CLI token commands

- deeplake/api/dataset.py
- deeplake/util/exceptions.py
- Include `ACTIVELOOP_TOKEN` auth method
- Single message in all cases
> [AL-2252] Update user not logged in and transform errors

- deeplake/util/spinner.py
> Disable spinner with verbose = False

- deeplake/__init__.py
- Bump version to 3.3.0 before release
> Bump version pre-release

- deeplake/integrations/mmdet/mmdet_.py
- deeplake/integrations/pytorch/pytorch.py
Added support for persistent_workers in deeplake mmdet integration
> Added support for persistent_workers

- deeplake/api/tests/test_polygons.py
- deeplake/core/chunk/uncompressed_chunk.py
> [AL-2268] Fix rechunk issue with poylgons

- deeplake/api/tests/test_text.py
- deeplake/core/chunk_engine.py
- deeplake/core/serialize.py
* Fix bug when appending with json tensor
> [AL-2247] Fix bug when appending with json tensor

- deeplake/__init__.py
> Bump version after release

- deeplake/core/dataset/dataset.py
- deeplake/core/query/test/test_query.py
> [AL-2252] Fix materialization for links

- README.md
- deeplake/api/tests/test_api.py
- deeplake/htype.py
- docs/source/Htypes.rst
- docs/source/_static/csv/htypes.csv
Added `embedding` htype and made minor readme updates
> Add embedding

- deeplake/__init__.py
- Bump staging version to 3.3.3
> Bump version post release

- .gitignore
- deeplake/core/chunk_engine.py
- deeplake/core/tensor.py
- deeplake/core/transform/test_transform.py
- Fix `pad_data_in` for transforms
> [AL-2267] Fix transform pad_data_in

- deeplake/api/dataset.py
> fix typo in dataset.py

- README.md
> updated readme with vector db phrasing and comparisons

- deeplake/core/dataset/dataset.py
> ds.extend speedup

- deeplake/core/dataset/dataset.py
- docs/source/Tensor-Query-Language.rst
Updating docs based on the restriction for Indra that is being lifted.
> Fixed restrictions in docs

- setup.py
> bump libdeeplake version to 0.0.52

- deeplake/core/dataset/deeplake_query_dataset.py
- deeplake/core/tests/test_deeplake_indra_dataset.py
- deeplake/enterprise/libdeeplake_query.py
- deeplake/requirements/tests.txt
- setup.py
- Create `DeeplakeQueryDataset` based on TQL api if the query is filter or not.
- If the tensor is not accessible in `deeplake_ds` try to get it from `indra_ds`.
> Expose indra virtual tensors in deeplake

- deeplake/__init__.py
> Bump version before release

- deeplake/api/dataset.py
- deeplake/core/storage/s3.py
> fixed ds slowdown

- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- deeplake/core/vectorstore/vector_search/indra/indra_vector_search.py
> added deeplake to indra translation

- deeplake/api/tests/test_api.py
> Test ds.log

- deeplake/core/dataset/deeplake_query_dataset.py
- deeplake/core/dataset/deeplake_query_tensor.py
- deeplake/core/tensor.py
- deeplake/core/tests/test_deeplake_indra_dataset.py
Fixed `.tensors`, `.summary()` and `.data()` methods for Indra ds/tensor wrappers.
> Virtual tensors cleanup

- deeplake/core/link_creds.py
- deeplake/core/storage/azure.py
> Added 2 fixes

- deeplake/core/tests/test_deeplake_indra_dataset.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/indra/indra_vector_search.py
- deeplake/enterprise/test_pytorch.py
- deeplake/enterprise/test_query.py
- deeplake/enterprise/test_tensorflow.py
- deeplake/tests/dataset_fixtures.py
- setup.py
changed to run half of the indra tests on local storage
upgraded libdeeplake version
> change some tests run on local ds

- deeplake/api/tests/test_api.py
- deeplake/api/tests/test_link.py
- deeplake/core/chunk_engine.py
- deeplake/core/tensor.py
- Get shapes of multiple samples as a numpy array
> [AL-2288] tensor.shapes method

- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- deeplake/core/vectorstore/vector_search/dataset/test_dataset.py
- deeplake/core/vectorstore/vector_search/indra/test_indra.py
- deeplake/core/vectorstore/vector_search/indra/vector_search.py
- deeplake/core/vectorstore/vector_search/python/vector_search.py
> Fixed tests and removed unecessary params from some functions

- deeplake/enterprise/convert_to_libdeeplake.py
> Cleanup indra

- deeplake/core/dataset/dataset.py
- deeplake/core/transform/transform.py
- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- deeplake/core/vectorstore/vector_search/utils.py
- deeplake/util/bugout_reporter.py
> Added support for images

- deeplake/core/transform/test_transform.py
- deeplake/core/transform/transform.py
- Fix transform error index in case of checkpointing to reflect already processed samples.
> Transform update for vector store

- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- deeplake/core/vectorstore/vector_search/dataset/test_dataset.py
- Changed tensor check function to support backwards compatibility
> Tweaked tensor check to support backwards compatibility

- setup.py
update libdeeplake version in the new version fixed sequence(link(type)) data access
> bump libdeeplake version to 0.0.57

- deeplake/integrations/pytorch/common.py
> [AL-2313] Empty sequences

- setup.py
> bump libdeeplake version to 0.0.58

- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- deeplake/core/vectorstore/vector_search/utils.py
- deeplake/core/vectorstore/vector_search/vector_search.py
This PR addresses edge case when we specify only sql query without any embedding_data or embedding.
> DeepLake vector store fixes

- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- docs/source/Vector-Store.rst
- docs/source/deeplake.core.vectorstore.rst
- Update docs to account for DeepLakeVectorStore -> VectorStore rename
- Dummy examples in docs instead of placeholders
- Fix vector store case with only user-defined embedding tensors
> Vector store docs update + minor fix

- deeplake/core/query/test/test_query.py
- deeplake/core/storage/azure.py
- deeplake/util/exceptions.py
- Pass creds and token from main dataset to subdir for saving views
> [BUGFIX] Azure view saving fix

- setup.py
> Bump libdeeplake version.

- deeplake/core/dataset/dataset.py
- deeplake/core/io.py
- deeplake/core/transform/test_transform.py
- deeplake/integrations/pytorch/dataset.py
- deeplake/integrations/pytorch/pytorch.py
- deeplake/util/transform.py
- Catch all exceptions in transforms.
- Set cache size for `ds.pytorch` so at least one chunk can exist in cache at a time.
> [AL-2318] [AL-2319] Transform and pytorch update

- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- Accept UUIDs as ids in vector store
> [AL-2327] VectorStore accept UUID as ids

- deeplake/api/tests/test_rechunk.py
- deeplake/api/tests/test_update_samples.py
- deeplake/core/chunk_engine.py
- deeplake/core/dataset/dataset.py
- deeplake/core/linked_chunk_engine.py
- deeplake/core/tests/test_deeplake_indra_dataset.py
- deeplake/core/transform/test_transform.py
- deeplake/core/transform/transform_dataset.py
- deeplake/enterprise/test_pytorch.py
- deeplake/enterprise/test_query.py
- deeplake/enterprise/test_tensorflow.py
- deeplake/tests/dataset_fixtures.py
- deeplake/tests/path_fixtures.py
- deeplake/util/chunk_engine.py
- docs/source/Datasets.rst
- `ds.update` atomic method for updating multiple tensors.
> [AL-2321] [AL-2323] ds.update

- deeplake/core/tensor_link.py
- deeplake/util/scheduling.py
> [BUGFIX] Fix random split

- deeplake/__init__.py
> [Tiny] Removed reporting when importing deeplake

- .github/workflows/lint.yml
- .github/workflows/test-pr-on-label.yml
- .github/workflows/test-push.yml
- Run only **3.10** on **Windows**, **Mac OS**, **Linux** tests on branch commits,
- Run full versioned tests only on `PRs` labeled `trigger-test` , `main` commits and `release/**` commits. Also do not delete trigger-test label after it is added
- Add concurrency groups for workflows: if there is running workflow for one event, next will cancel previous itself and then only start
- Change **linter** workflow python version to **3.10**.
> Edit workflows

- deeplake/core/dataset/dataset.py
* Add batch extends
* Add ignore errors arg
* Some fixes
> [AL-2200] ds.extend improvements

- deeplake/core/dataset/deeplake_cloud_dataset.py
- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- deeplake/core/vectorstore/vector_search/dataset/test_dataset.py
- deeplake/core/vectorstore/vector_search/indra/query.py
- deeplake/core/vectorstore/vector_search/utils.py
- deeplake/util/tensor_db.py
- Added logic to use an automatically-inferred exec_option based on the vector store's storage location
- Removed redundant tests and added comments to exception tests so it's clearer what combination of invalid parameters is being tested and why
- Updated `return_tensors` so they play more nicely with views and cases where the users want to return the embedding tensor.
> Auto params

- deeplake/api/tests/test_update_samples.py
- deeplake/core/chunk_engine.py
- Fixes some corruptions occurring if sample updates fail.
> [AL-2333] Fix updates

- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- Improved auto-params so that if the auto exec_option is used, and a user specifies a UDF filter, the exec_option automatically switches to python in order to avoid errors.
> Auto params improvement

- deeplake/core/lock.py
- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/utils.py
- Made VectoStore module work with exec_option = None during initialization
- Edits to locks bugs
> Hotfixes for Vector Store

- deeplake/__init__.py
> Bump version to 3.6.11

- deeplake/__init__.py
- deeplake/core/dataset/dataset.py
- deeplake/core/transform/transform.py
- deeplake/util/access_method.py
- deeplake/util/spinner.py
- deeplake/util/transform.py
- Fixes for spinner
- Fixes for dataset copy
> Fixes for downloading dataset

- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- deeplake/core/vectorstore/vector_search/dataset/test_dataset.py
- deeplake/core/vectorstore/vector_search/utils.py
Fixed the following failing tests:
1. deeplake/core/vectorstore/test_deeplake_vectorstore.py::test_delete
2. deeplake/core/vectorstore/test_deeplake_vectorstore.py::test_ingestion
3. deeplake/core/vectorstore/test_deeplake_vectorstore.py::test_parse_add_arguments
> Fix failing VectorStore tests

- deeplake/__init__.py
> Bump deeplake version to 3.6.13

- deeplake/core/dataset/dataset.py
- deeplake/core/dataset/deeplake_query_dataset.py
- deeplake/enterprise/dataloader.py
- deeplake/enterprise/dummy_dataloader.py
- setup.py
Added ignore_errors flag to pass to enterprise dataloader which will sign that dataloader needs to ignore all errors related to samples being corrupted to invalid linked. It will collect all that information and show in `dl.summary` table
At the moment we will ignore entire batch containing invalid sample with the further improvement it will reflect to the invalid sample row instead of ignoring the whole batch
As at the moment we ignore entire batch instead of just the row it may impact on the data which is passed to the training model it only reflects at the moment when the batch sizes are big enough and the incorrect samples normally distributed cases that may decrease training accuracy
> AL-2349  Add ignore_errors flag to .dataloader()

- deeplake/core/index/index.py
- deeplake/util/scheduling.py
> [AL-2365] Optimize dataloader creation

- deeplake/core/dataset/deeplake_query_tensor.py
- deeplake/core/tests/test_deeplake_indra_dataset.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
> [AL-2350] Indra returns polygons differently than python

- deeplake/__init__.py
> Bump version post-release

- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- deeplake/core/vectorstore/vector_search/indra/index.py
- deeplake/core/vectorstore/vector_search/indra/tql_distance_metrics/distance_metric.py
- deeplake/core/vectorstore/vector_search/vector_search.py
> Ad indexed search

- deeplake/util/storage.py
- setup.py
- [x ] Bug fix (non-breaking change which fixes expected existing functionality)
initialize used creds for S3 storage provider so indra will know which credentials is needed during credentials exchange
> [AL-2373] Init used creds

- deeplake/api/dataset.py
- deeplake/api/tests/test_api.py
- deeplake/core/query/test/test_query.py
- deeplake/core/vectorstore/deeplake_vectorstore.py
> Error out for invalid path in deeplake.delete

- deeplake/enterprise/dataloader.py
- deeplake/enterprise/test_pytorch.py
- setup.py
length of dataloader was incorrect if we were trying to iterate over imbalanced dataset
> Fix sub-dataset length calculation

- deeplake/__init__.py
> Updated version to 3.6.19

- deeplake/core/dataset/dataset.py
> [AL-2392][BUGFIX] ds.pop() not working as expected

- deeplake/core/storage/lru_cache.py
> [AL-2402] Fix LRUCache unpickle

- deeplake/constants.py
- deeplake/core/dataset/dataset.py
- deeplake/enterprise/test_query.py
When calling `dataset.save_view()`, the default messages stored in the view should be the query itself (truncated if the query is too long)
> [AL-2400] Set query as default view message

- deeplake/util/spinner.py
> [AL-2401] Fix spinner closed IO error after pytest exit

- deeplake/api/tests/test_api.py
- deeplake/core/dataset/dataset.py
- deeplake/core/transform/test_transform.py
- deeplake/core/transform/transform.py
- deeplake/util/exceptions.py
- deeplake/util/transform.py
- Suggest `ignore_errors` flag if any sample level error occurs in `ds.extend` or transforms.
> [AL-2332] Suggest ignore_errors flag in extend and transform

- setup.py
> bump libdeeplake version to 0.0.71

- deeplake/__init__.py
> Bump release version

- setup.py
> bump libdeeplake version to 0.0.72

- deeplake/enterprise/test_pytorch.py
- setup.py
> Libdeeplake 0 0 73

- deeplake/core/vectorstore/vector_search/dataset/dataset.py
In one of the latest PRs, I introduced this change while being not aware of that this functionality is available only on latest numpy release: `embedded_data = np.vstack(embedded_data, dtype=np.float32)`.  Fixed this, using old way of assining dtypes in numpy: `embedded_data = np.vstack(embedded_data).astype(dtype=np.float32)`
> Vectorstore numpy version fix

- deeplake/__init__.py
> Update version to 3.6.23

- .github/workflows/test-push.yml
Referenced github action branch was removed so reference needs to be updated
> Fixed failing build

- deeplake/enterprise/convert_to_libdeeplake.py
- deeplake/enterprise/libdeeplake_query.py
> correct indent

- deeplake/__init__.py
- deeplake/enterprise/dataloader.py
Post-release version upgrade plus ran python formatter
> Updated version after 3.6.25 release

- deeplake/__init__.py
> Updated version number after 3.6.26 release

- deeplake/core/storage/s3.py
Apparently s3 client can't handle large bytearray objects, but it's ok with bytes object (maybe because bytes are immutable). Switching to bytes allows uploading large files, while not changing other logic. Also bytes are immutable, so performance wise it should be better choice here.
> Fixed large file upload, by passing bytes instead of bytearray.

- deeplake/enterprise/util.py
- setup.py
> enable python3.11 for linux dists

- deeplake/enterprise/libdeeplake_query.py
- deeplake/enterprise/test_query.py
Running query on already queried dataset, was raising error.
> Fixed query chaining.

- deeplake/core/transform/test_transform.py
- deeplake/core/transform/transform_dataset.py
- deeplake/util/exceptions.py
- deeplake/util/transform.py
- Currently `dataset.extend` method is not supported in transforms, this PR adds that functionality.
> [AL-2414] `ds.extend` for transforms

- deeplake/util/version_control.py
- We have a recursive function that merges commit node maps
- This hits python's recursive limit at ~ 1K commits
- Change to iterative implementation
- Closes #2596
> [AL-2413] Iterative implementation of merging node maps

- deeplake/core/dataset/dataset.py
- deeplake/core/dataset/deeplake_query_dataset.py
- deeplake/enterprise/dataloader.py
- setup.py
added verbose argument to libdeeplake dataloader
> added verbose argument to ds.dataloader

- deeplake/core/tests/test_vdb_indexes.py
> test_vdb_indexes.py::Test case fix.

- deeplake/api/tests/test_api.py
> Mark flaky extend stress test

- deeplake/__init__.py
> Updated version to 3.7.1

- deeplake/__init__.py
- deeplake/core/dataset/deeplake_query_tensor.py
> Virtual tensor fix

- deeplake/__init__.py
> Updated version for 3.7.2 release

- setup.py
> bump libdeeplake version to 0.0.79

- deeplake/enterprise/dataloader.py
- docs/source/_static/csv/installation.csv
- setup.py
1. fixed single process dataloader iterator creation
2. added libdeeplake to default extras list
> added libdeeplake to default extras list

- deeplake/util/spinner.py
Spinner disappears the terminal cursor if the taks is less than 2second. Fixed that.
> Fixed cursor disappear on fast spinners.

- deeplake/__init__.py
> Updated version for next release

- deeplake/__init__.py
> Updated version post-release

- deeplake/core/dataset/dataset.py
> Better view saving error message

- deeplake/core/vectorstore/deep_memory.py
- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/test_deepmemory.py
- deeplake/core/vectorstore/vector_search/indra/search_algorithm.py
- docs/source/deeplake.VectorStore.rst
- docs/source/index.rst
- [X ] Bug fix (non-breaking change which fixes expected existing functionality)
In this PR I am adding support for retrieving score tensor during deep memory search and also fixing documentation failure related to VectorStore
> Deep Memory virtual tensors support

- deeplake/core/dataset/dataset.py
- deeplake/core/vectorstore/vector_search/indra/search_algorithm.py
- setup.py
> Deep Memory search speed up

- deeplake/api/tests/test_views.py
- deeplake/core/compression.py
- deeplake/core/dataset/dataset.py
- Fully support saving views of views
- Sub-views will be stored under parent dataset as well
> Saving views of views

- docs/source/Vector-Store.rst
> VectorStore docs fix

- deeplake/core/vectorstore/deep_memory.py
> deep memory typo fix

- deeplake/__init__.py
Updates next version after release
> Post-release version upgrade

- deeplake/__init__.py
Standard post-release version update
> Updated deeplake version for next release

- deeplake/core/tests/test_deeplake_indra_dataset.py
- deeplake/enterprise/dataloader.py
- deeplake/integrations/pytorch/shuffle_buffer.py
- setup.py
> dataloader signature changes

- deeplake/api/tests/test_api.py
- deeplake/api/tests/test_api_with_compression.py
- deeplake/core/chunk_engine.py
- deeplake/core/transform/transform_dataset.py
- deeplake/htype.py
> Remove default image dtype

- deeplake/integrations/pytorch/dataset.py
> Fixed: name 'TorchDataset' is not defined

- deeplake/core/dataset/dataset.py
- deeplake/core/tensor.py
- deeplake/core/vectorstore/deeplake_vectorstore.py
> linter fixes

- deeplake/core/dataset/dataset.py
- deeplake/core/index_maintenance.py
- deeplake/core/tensor.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
> - Adding @requires_libdeeplake to test cases. 

- deeplake/constants.py
> fixing index threshold

- deeplake/constants.py
- deeplake/core/vectorstore/deep_memory.py
- deeplake/core/vectorstore/deeplake_vectorstore.py
- deeplake/core/vectorstore/deepmemory_vectorstore.py
- deeplake/core/vectorstore/vector_search/dataset/__init__.py
- deeplake/core/vectorstore/vector_search/dataset/dataset.py
- deeplake/core/vectorstore/vector_search/dataset/test_dataset.py
- deeplake/core/vectorstore/vector_search/indra/search_algorithm.py
- deeplake/requirements/plugins.txt
- docs/source/Deep-Memory.rst
- docs/source/Vector-Store.rst
- docs/source/conf.py
- docs/source/deeplake.VectorStore.rst
1. Changed default rate_limiter behavior, if it is not specified or partially specified we auto populate other parameters.
2. Fixed docs
3. Changed printings in deep_memory and made them more clear
4. Changed deep_memory search to be local (temporary change, while tensor_db is not fixed)
> Deepmemory fixes

- deeplake/auto/structured/dataframe.py
-- Fixed edge case in previous PR
> [BUGFIX] Fix bug with params in ingest_dataframe

- deeplake/api/tests/test_dataset.py
- deeplake/core/chunk_engine.py
- deeplake/core/dataset/dataset.py
- deeplake/enterprise/convert_to_libdeeplake.py
- deeplake/enterprise/test_query.py
- deeplake/requirements/common.txt
This PR moves the token auto fetching from into deep lake level, so that if you are logged in, you no longer need to specify token when you run tql query
> Fetching token from env during deeplake dataset initialization

- deeplake/__init__.py
> Updated next version to 3.8.6

- deeplake/__init__.py
> Updated next version to 3.8.7

- deeplake/client/test_client.py
- deeplake/client/utils.py
- deeplake/tests/dummy_data/deep_memory/precomputed_jobs_list.txt
In case when deepmemory yields no improvement, in the list_jobs, print_status, we were showing 0% recall instead of the actual recall value. Also fixed some naming typos
> Deep Memory recall fix

- deeplake/__init__.py
> Update version for next release

- deeplake/__init__.py
Updates next version after release
> Post-release version update

- deeplake/core/dataset/dataset.py
- Using `len(ds)` internally produces 
```
WARNING:root:The length of tensors in the dataset is different. The len(ds) returns the length of the smallest tensor in the dataset. If you want the length of the longest tensor in the dataset use ds.max_len.
```
- Avoid this by using `ds.__len__(warn=False)` instead.
> Avoid `len(ds)` warnings internally

- deeplake/client/config.py
- deeplake/client/managed/managed_client.py
- deeplake/client/utils.py
- deeplake/util/exceptions.py
If the managed database returns a job status response instead of the full data, the client needs to poll the status API until it gets the response
Does not give user feedback on the overall process, is that OK?
Polls every 5 seconds rather than using a long-polling technique
> Support managed API returning a "job status" response

- deeplake/api/dataset.py
- deeplake/api/tests/test_api.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- `deeplake.like` in-place (with `overwrite=True`) was not working correctly because the tensor would be deleted before the new one is created.
- Load tensor data into memory prior to tensor creation to avoid this.
> In-place `deeplake.like`

- deeplake/api/dataset.py
- deeplake/core/storage/s3.py
- Overwrites on S3 can fail without raising errors but with errors in the server response.
- Check the response so that the errors do not go unnoticed.
> Make S3 overwrite fails visible

- deeplake/core/tests/test_deeplake_indra_dataset.py
- setup.py
> bump libdeeplake version to 0.0.97

- deeplake/__init__.py
Post-release update of next version
> Update next version to 3.8.16

- deeplake/core/chunk/chunk_compressed_chunk.py
- deeplake/core/transform/transform_dataset.py
> Transform speedup and bugfix

- deeplake/core/transform/transform.py
- deeplake/util/transform.py
- Exceptions returned from different processes lose their traceback on pickling, confusing users.
- Return the traceback text from the workers as well and print it to make the context visible.
> Better transform error propagation

- deeplake/api/read.py
- deeplake/core/sample.py
> Add timeout parameter for reading http links

- deeplake/util/storage.py
- [x ] Bug fix (non-breaking change which fixes expected existing functionality)
Fix the case of s3 client used creds detection
> fix correct creds used

- setup.py
> bump libdeeplake to 0.0.99

- .github/workflows/test-push.yml
> v4 CI Tests

- deeplake/api/dataset.py
- deeplake/auto/unstructured/image_classification.py
- deeplake/client/client.py
- deeplake/client/utils.py
- deeplake/util/exceptions.py
Now that the CLI has been removed, there is no "log in" action anymore, only passing tokens. 
This fixes exception error messages, removes a now-unused exception, and fixes method docs
> Removed use of the term "log in" and references to the CLI "activeloop login"

- README.md
- README.zh-cn.md
Replaced slack invite link with https://slack.activeloop.ai
> Updated slack links

- deeplake/core/dataset/deeplake_query_tensor.py
- setup.py
> Use libdeeplake batch requests for getting bytes.

- deeplake/core/storage/s3.py
> fix of An error occurred (400) when calling the HeadObject operation

- setup.py
> bump libdeeplake version to 0.0.107

- deeplake/core/tensor.py
- deeplake/core/tests/test_vdb_indexes.py
> EF_Search Setting in Deeplake. 

- deeplake/core/storage/azure.py
> Improve pre-signed URL handling for Azure

- deeplake/api/dataset.py
Very minor change in the docs.
> Removed coco references from the "ingest_dataframe" docs

- setup.py
> bump libdeeplake version to 0.0.108

- deeplake/auto/structured/dataframe.py
- deeplake/auto/tests/test_ingestion.py
-- Replaces nans in the dataframe so ingestion does not fail for cases when there are strings and nans in the same column. In general, since Deep Lake doesn't support nan explicitly, it's best to replace these values with None in all cases, even if it could work for arrays in some cases. 
-- How much is the slowdown for replacing nans in large dataframes
> Fix nan case for ingest_dataframe

- setup.py
> bump libdeeplake version to 0.0.109

- deeplake/core/compression.py
> Fixed av linter.

- deeplake/core/sample.py
- deeplake/core/transform/transform.py
The error messages from `numpy.frombuffer()` are vague. Catch and rethrow the exception with more context to improve troubleshooting 
Also adds more context to error messages coming from a section of the transform logic used in eval()
> Improved numpy conversion error messages

- deeplake/api/tests/test_views.py
- deeplake/core/tests/test_query.py
- deeplake/core/tests/test_vdb_indexes.py
- deeplake/core/transform/transform.py
- deeplake/core/vectorstore/deep_memory/test_deepmemory.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/enterprise/test_query.py
Mostly fixing test annotations, but also removed a try/catch that didn't seem to help debugging and possibly was impacting tests
> Better test annotations

- deeplake/core/dataset/dataset.py
- deeplake/core/dataset/deeplake_query_dataset.py
- deeplake/enterprise/__init__.py
- deeplake/enterprise/dataloader.py
- deeplake/requirements/common.txt
Fix the pillow version as mypy does not recognize new version stubs.
Avoid importing dataloader in deeplake/enterprise/__init__.py as it import torch and it takes ~1sec.
> Mypy and import fixes

- deeplake/core/dataset/dataset.py
- docs/source/Htypes.rst
- small tweak to docs to avoid user confusion 
-
> docs tweaks

- deeplake/core/compression.py
`deeplake.read` wasn't considering the 3rd dimension of the dicom image
> consider more than one frame in dicom

- deeplake/core/storage/s3.py
> catch SSLError as a connection error to retry

- setup.py
> bump libdeeplake version to 0.0.124

- deeplake/tests/client_fixtures.py
- setup.py
> bumb libdeeplake to 0.0.126

- setup.py
> bump libdeeplake version to 0.0.128

- deeplake/enterprise/convert_to_libdeeplake.py
> Add missing profile

- deeplake/client/client.py
- deeplake/util/exceptions.py
> [PLAT-441] Ensure messages are better propagated

- deeplake/auto/tests/test_kaggle.py
- deeplake/auto/unstructured/kaggle.py
Ensure the Kaggle tag is correctly passed to `ingest_kaggle()` before attempting to download it
> Validate kaggle tag before download

- deeplake/requirements/common.txt
Testing if numpy 2 is impacting backward compatibility tests
> Enforce numpy < 2

- deeplake/integrations/mmseg/mmseg_.py
1. removed from segmentation integration pre_eval implementation as we are not using it in our integration due to indices inconsistency coming from BatchSampler
2. make sure that mask is always a contiguous array and that the type is int64 as pytorchs cross_entropy_loss requires the target to be long
torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
> remove unnecessary functionalities

- deeplake/core/storage/s3.py
fixes the KeyError on S3 storage cleanup, when existence of `Error` key is checked in s3 api response.
> fix s3 deletion error

- docs/source/_extra/robots.txt
- docs/source/_extra/sitemap.xml
- docs/source/conf.py
> Added custom sitemap.xml file

- deeplake/requirements/tests.txt
Mostly looking at the backwards compatibility failures
> Remove pytest version constraint

- deeplake/auto/tests/test_ingestion.py
- deeplake/core/compression.py
- deeplake/core/vectorstore/test_deeplake_vectorstore.py
- deeplake/requirements/plugins.txt
- deeplake/requirements/tests.txt
- deeplake/util/dataset.py
Edited tensor sanitization function to replace spaces with _
> Tweaked sanitization for keys with spaces

- deeplake/integrations/mmdet/mmdet_.py
- deeplake/integrations/mmseg/mmseg_.py
> Propagate drop last

- deeplake/core/dataset/dataset.py
> Group index fix

- deeplake/auto/unstructured/kaggle.py
> fix error 'type' object is not subscriptable

- setup.py
> bumb libdeeplake to 0.0.135

- deeplake/__init__.py
> Update verison for next release

- deeplake/core/tests/test_indra_dataset.py
- deeplake/enterprise/convert_to_libdeeplake.py
- deeplake/enterprise/test_query.py
Removed empty token check from deeplake ds to libdeeplake ds conversion. The token check will be fully done on libdeeplake side.
the users trying to run high-performance features still need to specify their token, so all the internal validations are done. In another case, they will get an empty token exception from libdeeplake.
as the token check is moved from the deeplake to libdeeplake. the corresponding tests are also moved to libdeeplake repository
> remove empty token check from deeplake

- deeplake/core/meta/encode/pad.py
- deeplake/core/tests/test_vdb_indexes.py
> fix padding for last element

- deeplake/integrations/mmseg/mmseg_.py
> fix images tensor name dict

- deeplake/integrations/mmseg/mmseg_.py
> fix linter

- setup.py
> bump libdeeplake version to 0.0.136

- deeplake/integrations/mm/mm_common.py
- deeplake/integrations/mmdet/mmdet_.py
- deeplake/integrations/mmseg/mmseg_.py
> [DEEP-215] mmseg get pipeline by priority

- setup.py
> bump libdeeplake version to 0.0.137

- deeplake/core/storage/s3.py
> [DEEP-220] add urllib3's SSLError to the retriable errors list

- deeplake/enterprise/test_pytorch.py
- setup.py
> bump libdeeplake version to 0.0.138

- deeplake/client/client.py
- deeplake/core/dataset/dataset.py
- deeplake/core/dataset/deeplake_cloud_dataset.py
- deeplake/core/vectorstore/dataset_handlers/dataset_handler_base.py
> Ensure username fetching logic is not token dependent

- deeplake/client/client.py
* Fix typehint in `deeplake/client/client.py`. Since list subscription is not supported until python 3.10, typehint like `list[str]` will cause exception.
related to this [commit](https://github.com/activeloopai/deeplake/commit/54d257562351042f53befa4d901b58a5a5ac21a5#diff-22e6ec7ca9f5b6e4042998857caea1bb5e9504cc6a6b6cb926672f7bdd85fb8f)
> Fix list typehint for python3.8 supports

- deeplake/core/storage/gcs.py
- deeplake/enterprise/convert_to_libdeeplake.py
> Correct propagation of scoped gcs creds

- deeplake/__init__.py
- deeplake/api/dataset.py
- deeplake/auto/tests/test_yolo_template.py
- deeplake/auto/unstructured/yolo/utils.py
- deeplake/auto/unstructured/yolo/yolo.py
Added method for exporting Deep Lake dataset in yolo format.
- Further improvements can be made to parallelize the data conversion or use the Deep Lake dataloader to read data faster
- Yolo utils was refactored slightly so bounding box reading method can be used in other places
- Method automatically find tensors to export, but they can also be specified manually
- Method automatically estimates bounding box format, if it's not provided
> Add method to export Deep Lake dataset as yolo annotations

- deeplake/auto/unstructured/yolo/yolo.py
- Fix bug related to image compression calculation in export_yolo
> Fix bug in export_yolo

- setup.py
> bumb libdeeplake to 0.0.142

- deeplake/util/object_3d/mesh.py
- docs/source/Htypes.rst
> Docs updates

- deeplake/core/compression.py
- deeplake/core/vectorstore/deep_memory/test_deepmemory.py
- deeplake/requirements/common.txt
- deeplake/requirements/plugins.txt
- deeplake/tests/path_fixtures.py
> changes to work with av 13.0.0

- setup.py
> bump libdeeplake version to 0.0.145

- deeplake/core/partial_reader.py
> Fix partial read

- deeplake/core/vectorstore/deep_memory/test_deepmemory.py
> Mock out actual training result

- deeplake/core/chunk/sample_compressed_chunk.py
- deeplake/core/compression.py
- deeplake/core/sample.py
- deeplake/requirements/common.txt
- deeplake/requirements/plugins.txt
- deeplake/tests/common.py
- deeplake/util/downsample.py
- deeplake/util/exif.py
- deeplake/util/image.py
> Upgrade pillow

- deeplake/util/exceptions.py
- deeplake/util/tag.py
> Process hub path

- deeplake/core/storage/lru_cache.py
> local storage

- deeplake/api/tests/test_api.py
- deeplake/util/path.py
> strip dataset name

- pyproject.toml
> added pyproject for poetry support

- setup.py
> bump libdeeplake version to 0.0.146

- pyproject.toml
> strict numpy requirement

- deeplake/api/dataset.py
- deeplake/auto/structured/dataframe.py
- deeplake/auto/tests/test_ingestion.py
- deeplake/client/utils.py
- deeplake/core/chunk/chunk_compressed_chunk.py
- deeplake/core/chunk/uncompressed_chunk.py
- deeplake/core/chunk_engine.py
- deeplake/core/tensor.py
- deeplake/core/tests/test_indra_dataset.py
- deeplake/integrations/mmseg/mmseg_.py
- deeplake/requirements/plugins.txt
- deeplake/util/exceptions.py
- deeplake/util/version_control.py
- deeplake/util/video.py
- pyproject.toml
Fixed the dependent installment process
> change build backend

- setup.py
> bump libdeeplake version to 0.0.147

- .readthedocs.yaml
Include html output for download on readthedocs site
> Add htmlzip to readthedocs site

- deeplake/core/dataset/dataset.py
-  Bug fix (non-breaking change which fixes expected existing functionality)
added missing index params in __getstate__ method which was causing issues during dataset access in the multiprocessing context. Fixes issue reported here #2977
> added missing property in get/set state

- python/deeplake/__init__.py
- python/deeplake/__init__.pyi
- python/deeplake/types.py
- python/deeplake/types.pyi
> v4.0.1 Release.

- setup.py
> bump libdeeplake version to 0.0.148

- setup.py
> bump libdeeplake version to 0.0.149

- deeplake/enterprise/convert_to_libdeeplake.py
- deeplake/integrations/pytorch/common.py
- deeplake/util/dataset.py
> minor fixes

- deeplake/__init__.py
- pyproject.toml
Updating the version for next release
> Updated versions for 3.9.32 release

- deeplake/util/pretty_print.py
> [DEEP-454] fixed ds.summary with new json implementation

- deeplake/util/scheduling.py
> View schedule fix 

- pyproject.toml
- setup.py
> make libdeeplake dependency to always download the latest release

- deeplake/enterprise/convert_to_libdeeplake.py
fixed the bug related to running dataloader on azure connected dataset view
> fix azure view loading

- python/deeplake/__init__.py
- python/deeplake/__init__.pyi
- python/deeplake/ingestion/__init__.py
- python/deeplake/ingestion/coco/exceptions.py
- python/deeplake/ingestion/coco/ingest_coco.py
- python/deeplake/integrations/constants.py
- python/deeplake/integrations/mm/exceptions.py
- python/deeplake/integrations/mm/get_indexes.py
- python/deeplake/integrations/mm/ipc.py
- python/deeplake/integrations/mm/mm_common.py
- python/deeplake/integrations/mm/mm_runners.py
- python/deeplake/integrations/mm/upcast_array.py
- python/deeplake/integrations/mm/warnings.py
- python/deeplake/integrations/mm/worker_init_fn.py
- python/deeplake/integrations/mmdet/__init__.py
- python/deeplake/integrations/mmdet/mmdet_.py
- python/deeplake/integrations/mmdet/mmdet_dataset_.py
- python/deeplake/integrations/mmdet/mmdet_utils_.py
- python/deeplake/integrations/mmdet/test_.py
- python/deeplake/integrations/mmseg/__init__.py
- python/deeplake/integrations/mmseg/compose_transform_.py
- python/deeplake/integrations/mmseg/mmseg_.py
- python/deeplake/integrations/mmseg/mmseg_dataset_.py
- python/deeplake/integrations/mmseg/test_.py
- python/deeplake/schemas.pyi
- python/deeplake/tql.pyi
- python/deeplake/types.pyi
> v4.1.2 Release

- python/deeplake/__init__.py
- python/deeplake/__init__.pyi
> v4.1.3 Release

- deeplake/enterprise/convert_to_libdeeplake.py
> fixed storage provider error when the local_cache is specified

- deeplake/core/storage/azure.py
> update client after the creds exchange

- deeplake/__init__.py
- deeplake/core/dataset/indra_dataset_view.py
- pyproject.toml
> Updated versions for 3.9.36 release

- deeplake/__init__.py
- pyproject.toml
> Updated versions for 3.9.37 release

- README.md
Fixed readme documentation links.
> Fixed readme docs links.

- deeplake/core/storage/azure.py
> added retry

- deeplake/__init__.py
- pyproject.toml
> Updated versions for 3.9.39 release

- deeplake/core/storage/azure.py
- deeplake/integrations/__init__.py
- deeplake/integrations/labelbox/converters.py
- deeplake/integrations/labelbox/deeplake_utils.py
- deeplake/integrations/labelbox/labelbox_.py
- deeplake/integrations/labelbox/labelbox_converter.py
- deeplake/integrations/labelbox/labelbox_utils.py
- deeplake/integrations/tests/test_labelbox.py
- deeplake/util/storage.py
> Labelbox integration refactor

- deeplake/__init__.py
- pyproject.toml
> Updated versions for 3.9.40 release

- deeplake/__init__.py
- pyproject.toml
> Updated versions for 3.9.41 release

- deeplake/__init__.py
- pyproject.toml
> Updated versions for 3.9.42 release

- deeplake/integrations/mmlab/segmentation/mmseg_.py
> Fix palette

- deeplake/__init__.py
- deeplake/visualizer/visualizer.py
- pyproject.toml
Serve OPTIONS requests in local server.
> Fixed ds.visualize for local datasets.

- python/deeplake/__init__.py
- python/deeplake/__init__.pyi
Fixed bugs:
- Permanent redirect error message from S3 client on different location resource loading
- Incorrect dtype in virtual columns
- Stuck or crash when doing multiple iterations with break
- Descriptive error message on network request failures
> v4.1.11 Release

- deeplake/__init__.py
- pyproject.toml
> Updated versions for 3.9.44 release

- python/deeplake/__init__.py
- python/deeplake/__init__.pyi
- python/deeplake/storage.py
- python/deeplake/storage.pyi
- python/deeplake/tql.py
- python/deeplake/tql.pyi
> v4.2.1 Release

- .github/workflows/langchain-tests.yaml
- .github/workflows/lint.yml
- .github/workflows/release-drafter.yml
- .github/workflows/test-push.yml
> Correctly disabled workflow files.

- python/deeplake/__init__.py
- python/deeplake/__init__.pyi
- python/deeplake/types.pyi
> v4.2.7 Release

- deeplake/__init__.py
- pyproject.toml
> Updated versions for 3.9.45 release

- deeplake/integrations/mmlab/segmentation/basedataset.py
- deeplake/integrations/mmlab/segmentation/basesegdataset.py
- deeplake/integrations/mmlab/segmentation/mmseg_.py
> Base mmsegmentation dataset

- deeplake/__init__.py
- pyproject.toml
> Updated versions for 3.9.50 release

- deeplake/__init__.py
- deeplake/core/tests/test_inverted_indexes.py
- pyproject.toml
> Update version for 3.9.51 release
