examples/fashion-mnist/train_pytorch.py
examples/fashion-mnist/train_tf_fit.py
examples/fashion-mnist/train_tf_gradient_tape.py
examples/fashion-mnist/upload.py
hub/collections/dataset/__init__.py
hub/collections/dataset/core.py

to_tensorflow and to_pytorch now work properly even when text labels present by converting such labels to ascii. 
Also, updated fashion-mnist code, which had stopped working after named_labels were added. Examples of conversion back from ascii to text are present in train_tf_gradient_tape.py and train_pytorch.py in fashion-mnist.

Added support for text labels in to_tensorflow, to_pytorch

---

hub/collections/client_manager.py

Now we access a custom invisible folder at the user root to save the tmp files
Closes #42

Fix bug with missing permission when using root /tmp

---

.github/workflows/locust.yaml

GitHub Actions triggered by pull_request events from forks do not have
permission to post comments to the base repo.
The fix for this is to use the pull_request_target event.
See official GitHub statement about pull_request_target:
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

Fix errors for Locust GitHub Action

---

examples/coco/upload_coco2017.py

Example contains default folder path to ```cifar10``` dataset. Correcting it to ```COCOdataset2017```

Correcting upload_coco2017.py

---

.github/workflows/locust.yaml

This should reduce any noise Locust may be creating on PRs that get
synchronized often while providing the same value for larger changes.

Locust now only pushes a summary when PR is opened

---

examples/eurosat.py
hub/api/dataset.py
hub/api/datasetview.py
hub/api/tests/test_converters.py

to_tensorflow now supports text labels, added tests as well. to_pytorch doesn't, as pytorch tensors can't hold strings/bytes
Also added both to converters to datasetview view.
Added Eurosat example that includes both of these things and would also be useful to Omdena users.

 Enhancements to converters

---

MANIFEST.in

fixes #142 
This patch adds a manifest file which can be used to add non-python files to the sdist tarball 
Local installation tested in a new environment 

Fix inclusion of non python files in sdist

---

hub/store/store.py

This patch adds an elif to check whether url starts with a single
(drive) letter followed by a ":" (colon), the way an absolute local path
in Windows looks like. The check uses regex to match any drive letter

Add windows local path to get_fs_and_path

---

hub/store/lru_cache.py
hub/store/store.py
hub/store/tests/test_store.py

fixes #217 and fixes #215 
The first patch updates the posixpath expanduser to use os.path.expanduser which works on both windows and Linux (posix like os). Also removes the fnctl and system mutex class as they are not being used and cause problems in Windows.
The second patch fixes the cache path in all OS and envs (s3, gcs, https, windows, posix, etc)
Tested on new AWS Windows Machine.

Update expanduser to work with windows

---

hub/schema/features.py
hub/schema/tests/test_tensor.py
hub/store/dynamic_tensor.py
hub/store/tests/test_dynamic_tensor.py

Gives error when both shape and max_shape are none.
Solved issue when the program unexpectedly crashes without User readable error, because of wrong user input.

Gives error when both shape and max_shape are none

---

hub/api/datasetview.py
hub/compute/transform.py

Fixes crashes in transform by changing shard size calculation to drastically reduce RAM usage with little difference in speed.
Now that the shard size is smaller there has also been a new issue with multithreading #321.

Fixes crashes in transform by changing shard size calculation

---

hub/api/objectview.py
hub/compute/ray.py
hub/compute/tests/test_transform.py
hub/compute/transform.py

Adding get_value before str_to_int, to handle cases like np.array("abc")

Fixes to transform to properly support cases such as np.array("abc")

---

README.md

Add the README Badge/Shield in the README.md
Question: Shall we put it as: `powered by Hub` OR `powered by activeloop.ai`?
Also, what should it redirect to when clicked? I will make necessary changes.
Currently, it says: `powered by Hub` and redirects to the Hub repository (as most python libs do).

add README Badge Section in README.md

---

benchmarks/benchmark_to_pytorch.py
hub/api/dataset.py
setup.py

Each process of data loader remembers the current chunk in python memory and uses it as a cache. This enabled us to skip huge pythonic overhead thus improving performance. 
This still does not work for dynamic tensors because we cannot request a multisample slice from datasets with dynamic tensors.

Faster pytorch dataset with current chunk logic

---

.circleci/config.yml

This PR fixes [twine upload pipeline](https://app.circleci.com/pipelines/github/activeloopai/Hub/1025/workflows/7060ecf1-0a4c-458d-8276-36ebdde2a297/jobs/1083) via adding `--skip-existing` tag to prevent version conflict.
This PR also remove some trailing spaces, newlines in `.circleci/config.yml`.
This PR will take effect on next tag release.
Currently PyPi doesn't allow package override and lead to `400 File already exists.` Although using build number for wheel versioning the wheel release succeeded, I got `400 Only one sdist may be uploaded per release.` when releasing sdist distribution.
Considered about [Semantic Versioning](https://semver.org/lang/zh-TW/), maybe release a newer version to fix bugs is more appropriate than overriding the old version.  Therefore in `config.yml` I …

ci: Fixes CI deployment pipeline

---

README.md

Updates the readme file with:
1. more direct and precise wording, .e.g. 
_from_
> You can access public datasets with a few lines of code.
_to_
> Access public datasets in Hub by following a straight-forward convention which merely requires a few lines of simple code. Run this excerpt to get the first thousand images in the MNIST database in the numpy array format:
2. a link to [CONTRIBUTING.md](CONTRIBUTING.md)
3. a direct link to registration
4. links with utm parameters for better tracking of the web app traffic
5. comments explaining code excerpts

Use more precise wording and fix mistakes in readme

---

docs/source/benchmarks.md

Changed typo "bellow" to "below", and moved the preposition after the noun. For more on why this is the gramatically correct order, see [this english stackexchange post](https://english.stackexchange.com/questions/609/which-is-correct-the-below-information-or-the-information-below)

Fix typo in benchmarks.md

---

.circleci/config.yml

Fixes #367, since the docker build step fails the issue exists.
According to [CircleCI document](https://circleci.com/docs/2.0/building-docker-images/), the build step have to add `- setup_remote_docker` for security reasons.

Fixes docker build issue

---

hub/api/dataset.py
hub/api/tests/test_dataset.py

Users can now specify dataset name at the time of creation. This is only useful for the visualizer and is irrelevant for datasets not stored on hub storage:-
```python
ds = hub.Dataset("username/dataset_url", schema=my_schema,  shape=(10,), name="my_dataset")
```
Dataset owners can also rename the dataset:-
```python
ds2 = hub.Dataset("username/dataset_url")
ds2.rename("new_name")
```
You can check the dataset name using:-
```python
print(ds.name)
```

Store dataset name in meta.json

---

hub/api/dataset.py

This pull request closes #477 
Changes were necessary due to the tensorflow 2.4.0 API update.

Changed tf.python.framework.tensor_spec.TensorSpec to tf.TensorSpec

---

hub/api/datasetview.py
hub/api/tests/test_dataset.py

Fixes to get_dictionary and added unit tests for the same

Fixes to get_dictionary

---

hub/compute/transform.py

@AbhinavTuli, I have edited the description of the transform computation as we discussed in Slack.

Edited message for transform computation

---

benchmarks/benchmark_zarr_hub.py

Added benchmarking files similar to that with TileDB, except this is for  Zarr.
For reproducibility, this also has been tested on a Google Colab Notebook environment.
The benchmarks are as follows:
```
Dataset:  activeloop/mnist with Batch Size:  70000
Performance of Zarr
Batch 1 dt: 0.3488335609436035
Time: 0.3494699001312256s
Performance of Hub (Stored on the Cloud):
Batch 1 dt: 1.3345892429351807
Time: 1.3362071514129639s
Performance of Hub (Stored Locally):
Batch 1 dt: 0.06419062614440918
Time: 0.06442713737487793s
Dataset:  activeloop/mnist with Batch Size:  7000
Performance of Zarr
Batch 1 dt: 0.2592613697052002
Batch 2 dt: 0.25765037536621094
Batch 3 dt: 0.2523312568664551
Batch 4 dt: 0.26584601402282715
Batch 5 dt: 0.26589441299438477
Batch 6 dt: 0.2726469039916992
Batch 7 dt: …
```

Added benchmarks for Zarr compared to Hub

---

hub/schema/tests/test_features.py

This is an initial attempt to improve test coverage by evaluating multiple arguments. This is achieved by using `@pytest.mark.parameterized` .
Currently the dtypes being tested are:
`uint32`, `int16`, `float32`, `float64`, `int8`, `int16`, `int32`, `double`
And the following are skipped for now:
`uint8`, `uint16`

Evaluate multiple arguments using pytest parameterized

---

benchmarks/benchmark_sequential_write.py

Related to #529. This contains the write benchmarks.
Note: For the benchmarking of hub cloud-based writing, one needs to be logged in from that terminal and change the user field accordingly.

Added sequential write benchmarks

---

hub/api/dataset.py
hub/api/integrations.py

This PR is a temporary fix for the refactoring of the Dataset Class.
Since the Dataset class is too heavy and proper refactoring would take a significant amount of time and resources, this is a stopgap solution in which certain functions that convert hub datasets to other frameworks and vice-versa have been relocated from the base Dataset class file `dataset.py` to a new file `integrations.py`. These functions are not imported when a Dataset object is created, however, if the user calls these functions, they are subsequently imported and used.
Closes #526

Refactored Dataset Class

---

README.md
README_CN.md
docs/source/concepts/dataset.md
docs/source/simple.md
docs/source/tutorials/new_api.md
examples/Use_Case_DL_crop_yield_prediction_dataset_with_Activeloop.ipynb
examples/basic.py
examples/big_image.py
examples/large_dataset_build.py
examples/mnist_upload_speed_benchmark.py
examples/new_api_intro.py
hub/api/dataset.py

Following up on a conversation with @AbhinavTuli and @mynameisvinn, I am creating a pull request to replace all mentions of `commit()` with `flush()`, as the `commit()` method is deprecated. Please let me know if I've missed anything or need to further replace anything else. Thank you!

Replaced commit() with flush() in documentation.

---

hub/api/compute_list.py
hub/api/dataset.py
hub/api/datasetview.py
hub/api/sharded_datasetview.py
hub/api/tests/test_dataset.py
hub/api/tests/test_sharded_dataset.py
hub/exceptions.py
hub/tests/test_exceptions.py

Adds advanced (cross shard) slicing to Sharded Dataset. Need to wait for #557 before merging to master.

Advanced slicing added for Sharded Dataset

---

README.md
README_TR.md

add README in Turkish

---

README.md

Changed `ds.commit()` to `ds.flush()` in README.md due to deprecation warning.

change ds.commit() to ds.flush() in README.md

---

examples/large_dataset_build.py
hub/store/shape_detector.py
hub/store/tests/test_shape_detector.py

Some of the assertion errors were confusing, thus, explanations have been added. Solves #611

Removed Assertions from shape_detector.py and added exceptions

---

conftest.py
hub/report.py

Did this by creating a session-level autouse Pytest fixture in `conftest.py` (at project root).
Removed unused import in `hub/report.py`.

Turned reporting off when tests are run

---

benchmarks/benchmark_sequential_write.py
hub/api/dataset.py
hub/api/datasetview.py
hub/api/integrations.py
hub/api/tensorview.py
hub/api/tests/test_dataset.py
hub/compute/ray.py
hub/compute/transform.py
hub/schema/bbox.py
hub/schema/class_label.py
hub/schema/deserialize.py
hub/schema/sequence.py
hub/schema/tests/test_features.py

to_tensorflow now works better with Text data.
ClassLabel and BBox schemas now support multiple ClassLabels and BBoxes. Better shape checks also added for both of these. Docstrings also improved. This should replace most usecases for Sequences

Improvements to to_tensorflow and BBox, Classlabel schemas

---

README_translations/README_CN.md
README_translations/README_FR.md
README_translations/README_ID.md
README_translations/README_KR.md
README_translations/README_TR.md

Simply changed the broken hyperlinks in the markdown files and rearranged the order of languages in some of the READMEs for uniformity. Closes #681

Fixed README  links

---

benchmarks/dnafrag_hub_backend.ipynb

A verbose notebook has been added which uses a modified version of the "dnafrag" package to compare Hub with TileDB backends.

Added ipynb file with benchmark tests for dnafrag package

---

hub/cli/auth.py
hub/report.py

This PR adds a `username:<Activeloop username>` tag to usage and crash reports from users who have opted into reporting.

Added tags to usage and crash reports

---

hub/api/tests/test_dataset.py
hub/store/dynamic_tensor.py

Convert dynamic tensor shape to tuple.

Fixed issue with resize in mode='a'

---

hub/api/dataset.py
hub/compute/tests/test_transform.py
hub/store/metastore.py

The below code earlier gave an error "AttributeError: 'Dataset' object has no attribute '_chunk_commit_map'"
```python
ds_transform = some_transform(iterable)
ds = ds_transform.store("abcd/ds_name")
ds = ds_transform.store("abcd/ds_name")
```
This has now been fixed.

Fixed an issue when overwriting transform datasets

---

hub/api/dataset.py
hub/api/dataset_utils.py
hub/api/datasetview.py
hub/api/tests/test_dataset.py

Filtered or subsets of Datasets stored as DatasetView can now be stored as new Datasets

Added store to DatasetView

---

hub/api/dataset.py
hub/api/datasetview.py
hub/api/integrations.py
hub/api/tests/test_converters.py
hub/schema/class_label.py
hub/schema/deserialize.py
hub/schema/tests/test_features.py

- to_pytorch now supports a new argument that only passes certain tensors to it and speeds up iteration time in case multiple extra tensors are present.
- caching present within to_pytorch has been improved to tensors with dynamic shapes (earlier it was saving only the current sample in the cache)
- changed default dtype of classlabel from uint16 to uint8

Improvements to to_pytorch

---

hub/api/dataset.py
hub/api/dataset_utils.py
hub/api/tests/test_dataset.py
hub/exceptions.py

Adds a check to see if the schema argument provided differs from the schema stored in the dataset

Schema check

---

hub/api/tests/test_api.py

This PR literally only adds a test for scalar samples. Thanks to #949's refactor :)
This test makes sure the following works:
```python
tensor = ds.create_tensor(...)
tensor.append(5)
tensor.extend([5, 10])
tensor.extend([])  # does literally nothing, and makes sure that len(tensor) doesn't change
```

add scalar samples test (it already passes :))

---

hub/api/dataset.py
hub/api/tensor.py
hub/api/tests/test_api.py
hub/core/index/index.py
hub/util/tests/test_split.py

Update `Dataset.__len__`, `Tensor.__len__` to account for length of an index. This is done via `Index.length` and `IndexEntry.length` (since they need the context for the length of the parent, they can't be `.__len__` methods)
```
>>> ds.data.numpy(aslist=True)
[1, 2, 3, 4, 5]
>>> len(ds[2:4])
2
>>> len(ds.data[[0,3]])
2
```
Bonus addition:
Add back the quotes to str(ds)'s path. `str(ds)` should now print `path` with the appropriate quotes.

[2.0] Change Dataset.__len__ and Tensor.__len__ to account for Index

---

hub/constants.py

with `USE_UNIFORM_COMPRESSION_PER_SAMPLE = True` this means that all compressed samples being ingested are decompressed and recompressed to keep tensor uniformity. This flag will simplify our development process, as well as move further away from a generic filesystem.
on the other hand, if `False`, ingestion is faster.
This PR proposes to keep tensor uniformity.

set `USE_UNIFORM_COMPRESSION_PER_SAMPLE` to `True`

---

hub/api/tests/test_api.py
hub/core/index/index.py
hub/core/tensor.py

Enables scalar outputs for `.numpy(aslist=True)`:
```
>>> tensor.numpy(aslist=True)
[1, 2, 3]
```
instead of:
```
>>> tensor.numpy(aslist=True)
[array(1), array(2), array(3)]
```

[2.0] Add scalar outputs for numpy(aslist=True)

---

hub/core/index/index.py

Removes usage of `@dataclass` for python 3.7 compatibility.

[2.0] Remove dataclass from index.py

---

hub/core/storage/s3.py

A readonly check was mistakenly included in `S3.__getitem__`, which doesn't modify and therefore is readonly-safe. This PR removes the throw here.

Remove readonly check on S3 __getitem__

---

hub/api/dataset.py
hub/api/tensor.py

When in a python REPL environment, Dataset isn't printed according to `__str__`, but actually `__repr__`. We may want to diverge these in the future, but for now we should alias them so it doesn't print as:
```
>>> ds
<Dataset object at 0x7f0e47de7670>
```

[2.0] Alias __repr__ to __str__ for Dataset and Tensor

---

hub/api/dataset.py
hub/api/tensor.py
hub/util/get_storage_provider.py

- Unify wording in Dataset/Tensor: "verbs _the_ dataset" instead of "verbs _a_ dataset". This may or may not be in line with google-docstring standard, but it's consistent with what we have elsewhere.
- Tensorflow docstring should say "tensorflow" and not "pytorch". Also added a link to the `tf.data.Dataset` docs
- Add `hub://` to the docstring for `storage_provider_from_path`, and update the wording.

[2.0] Minor improvements to docstrings

---

hub/api/tests/test_api_with_compression.py
hub/core/chunk_engine/read.py
hub/core/compression.py
hub/core/sample.py
hub/core/tests/test_compression.py
hub/integrations/pytorch.py

- Enables compression of grayscale images by squeezing the last dimension (assumed to be the channel dimension) when unambiguous, and restoring the shape when decompressing.

[2.0] Support compression for grayscale images

---

hub/integrations/pytorch.py
hub/integrations/tests/test_pytorch.py

On the fly Pytorch transforms are now performed in the main process, instead of using the worker pool. This leads to significant speed gains in most transform cases.

Faster Pytorch Transform

---

hub/api/tests/test_api.py
hub/core/index/index.py
hub/core/index/tests/test_index.py
hub/tests/common.py

This PR adds support for simple negative slicing and indexing. The first level of slicing will always work:
```
ds[-2:10:-3]
ds[5:-10:6]
ds[-100]
```
Multiple levels of slicing will work **only for positive slices**.
Slice composition at this level is not possible if we allow negatives, unless we use length information. The reason we don't do this is because the tensors are subject to change between indexing and access, and prematurely accessing length could lead to incorrect results.
```
ds[2::3][::2]
ds[10:15:3][1:2]
ds[::-3][::-3]
ds[-10::2][1:2]
ds[::3][-1] # negative integers after slices not allowed either
```
This PR also implements `assert_array_lists_equal`, which is used for testing equality of lists of numpy arrays, so we don't have to do a loop each time and so we can …

[2.0] Better negative indexing

---

hub/api/dataset.py

Local (or on-prem) datasets can be created without internet connection.

client initiated only for hub datasets

---

hub/integrations/pytorch_old.py
hub/integrations/tests/test_pytorch.py

Old pytorch dataloader doesn't support multiple num_workers, currently it will raise an implement error to add support later.

pytorch num_workers>0 for older python raises error

---

hub/api/tests/test_api.py

no changes, just added a test case (that already passes)

[small] update scalar test

---

hub/api/dataset.py
hub/api/tests/test_readonly.py
hub/core/chunk_engine.py
hub/core/storage/lru_cache.py

readonly method was failing when reading persistent data in readonly mode because LRU cache _insert_in_cache was calling check_readonly. i removed this check and added a test.

[small] Fix/2.0/readonly

---

hub/api/dataset.py
hub/api/tests/test_api.py
hub/api/tests/test_api_with_compression.py
hub/constants.py
hub/core/chunk_engine.py
hub/core/compression.py
hub/core/meta/tensor_meta.py
hub/core/sample.py
hub/core/tensor.py
hub/htypes.py
hub/integrations/tests/test_pytorch.py
hub/integrations/tests/test_tensorflow.py
hub/tests/common.py
hub/util/exceptions.py

before, `sample_compression=UNCOMPRESSED` was how you specify uncompressed tensors. instead, now it is: `sample_compression=None`.
also, if you are using an `image` `htype`, you are required to specify `sample_compression`, whether it be `None` or an actual compressor.
introduces a new `REQUIRE_USER_SPECIFICATION` constant that can be used by any htype property. if used, no default exists and the user must specify a value.
also removes all `chunk_compression` references for the time being.

update sample compression API 

---

hub/api/tests/test_api.py

made test go accross 2 chunks and cleaned it up a little bit

[small] Update/2.0/hub cloud test

---

hub/api/tests/test_api.py
hub/core/storage/s3.py

S3/hub cloud datasets with similar names was throwing errors during dataset creation.
This fixes it.
Earlier, the following blocks of code would have failed. They work now.
```python
ds1 = Dataset("hub://some_user/my_dataset_suffix")
ds2 = Dataset("hub://some_user/my_dataset")
```
```python
ds1 = Dataset("s3://some_bucket/my_dataset_suffix")
ds2 = Dataset("s3://some_bucket/my_dataset")
```

Fixes dataset creation bug with s3/hub cloud datasets having similar names

---

hub/integrations/pytorch.py
hub/integrations/pytorch_old.py
hub/integrations/tests/test_pytorch.py
hub/util/dataset.py

please also review #1024 as this branch is based on it and they're both really small
if you tried to use pytorch on a dataset in readonly mode it would fail. this fixes it and adds a test for future proof

[small] pytorch readonly error bug fix

---

hub/integrations/pytorch.py

New pytorch was failing for datasets larger than shared memory size. This fixes it.
self.all_shared_memory was earlier used to ensure that memory wasn't dereferenced, but the logic was changed and this is no longer required.

Small fix for Pytorch shared memory leak

---

hub/integrations/__init__.py
hub/integrations/pytorch_old.py
hub/util/exceptions.py

A recent windows update seems to have broken Python shared memory + multiprocessing.
For now, Windows will always use the old pytorch integration.

Windows always uses old pytorch integration now

---

hub/__init__.py
hub/util/bugout_reporter.py

Now, we create the parent directory using `os.makedirs` in a manner similar to the `write_token` method in `hub/client/utils.py`.

Fixes an issue in which reporting configuration file was not being created if its parent directory didn't exist.

---

hub/api/dataset.py
hub/api/tests/test_api.py

This is an alternate fix to the tensor creation bug encountered earlier. #1043 had fixed it partially, but in the old fix, if tensor creation failed due to an incorrect parameter such as wrong compression specified, the tensor would already be in the dataset's tensor list. Loading this dataset would then fail with a TensorDoesNotExistError as the actual tensor doesn't exist but the dataset's tensor list had it.
This PR rectifies the above issue.

Alternate fix for tensor creation bug

---

hub/integrations/pytorch/pytorch_old.py

The storage was getting reused across processes leading to s3 get issues in some cases. This fixes it and ensures each process uses a different storage.

Old pytorch multiprocessing bug fix

---

hub/api/tests/test_api.py
hub/tests/dataset_fixtures.py
hub/tests/storage_fixtures.py

right now hub cloud is throttling us when multiple circleci runs are doing tests. this is because all tests are ran with hub cloud, when in reality we only need 1 or 2 tests since it's exactly the same as s3.

[small] fix hub cloud throttling for tests

---

.circleci/config.yml

calls `activeloop reporting --off`  before running pytests on circleci

[small] turn off activeloop reporting during circleci tests

---

hub/client/client.py

This PR removes the link to the Dataset on https://app.activeloop.ai when a new Hub Dataset is created.

[small] Remove dataset link during creation of Hub datasets

---

hub/__init__.py
hub/api/dataset.py
hub/api/tests/test_api.py
hub/core/dataset.py
hub/core/meta/tensor_meta.py

added: 
```python
import hub
hub.dataset.like(...)
hub.like(...)  # alias
ds1 = ...  # assume ds1 has a tensor named "images"
ds2 = ...
ds2.create_tensor_like(ds1.images)  # does the same thing as `hub.like(...)` but for a single tensor
```

[small] implement `hub.like` in new api

---

hub/api/tests/test_api.py
hub/core/dataset.py
hub/util/exceptions.py

Add check for reserved names in .create_tensor().

Ban dataset attributes as tensor names

---

hub/client/log.py

Removes the default initialization of the logging configuration in the client. This sets the default to the default, so it should be harmless to remove.
Make sure to validate the CI output before merging.

Remove default logging code in client

---

hub/core/serialize.py
hub/core/storage/local.py

Makes chunk serialization faster. Noticed around a 2x speedup when populating local datasets, s3 uploads are also slightly faster but didn't notice as big a difference, probably due to the network speeds being the bottleneck on my machine.

Faster chunk serialization

---

hub/core/transform/transform.py

Move transform reporting to pipeline eval

---

hub/__init__.py
hub/api/tests/test_api.py
hub/client/client.py
hub/constants.py
hub/core/dataset.py
hub/core/meta/tensor_meta.py
hub/htype.py
hub/util/exceptions.py

renames `hub/htypes.py` -> `hub/htype.py`
```python
import hub
hub.htypes  # returns a list of all available htypes
``` 
just a cleaner api

[small] `hub.htypes` is a list of all htypes

---

hub/core/storage/lru_cache.py
hub/integrations/pytorch/pytorch_old.py
hub/integrations/tests/test_pytorch.py

Fixes an issue with pytorch old read only, fixes the old test to ensure that this doesn't break in the future.

Fixes an issue with pytorch old read only

---

hub/auto/unstructured/image_classification.py
hub/util/auto.py
hub/util/tests/test_auto.py

Few touch ups on Hub auto
Jupyter notebook fix: Addresses an issue when a non-supported file doesn't get skipped and stops ingestion
Temporarily remove numeric value from ingestion summary

auto refinement

---

hub/api/tests/test_api.py
hub/util/casting.py

https://activeloop.atlassian.net/browse/AL-1267

Treat size 1 arrays as scalars when casting

---

hub/core/compression.py
hub/core/tests/test_compression.py
hub/integrations/tests/test_pytorch.py
hub/integrations/tests/test_tensorflow.py
hub/tests/path_fixtures.py

Expect multiple SOF markers, pick the last one to find shape.

Multi - SOF jpeg fix

---

hub/tests/path_fixtures.py

lets you run `pytest .` without gcs creds. no functionality change, just fixes a headache

fix running tests fails when no gcs creds exist

---

hub/core/compression.py
hub/core/tests/test_compression.py
hub/requirements/common.txt
hub/requirements/requirements.txt

BC for dataset compressed with lz4.frame

lz4 backward compatibility

---

.circleci/config.yml

This PR brings back the "Linux Simple Test" for testing `hub` without plugins.

Bring back "Linux Timple Test"

---

hub/api/tests/test_pickle.py
hub/core/dataset/dataset.py
hub/core/dataset/hub_cloud_dataset.py

Ensures that the dataset agreement is only loaded once for each Dataset instance

Fix to ensure agreement isn't reloaded for each slice of dataset

---

hub/core/compute/process.py
hub/core/compute/provider.py
hub/core/compute/ray.py
hub/core/compute/serial.py
hub/core/compute/thread.py
hub/core/dataset/dataset.py
hub/core/query/__init__.py
hub/core/query/filter.py
hub/core/query/query.py
hub/core/query/test/test_query.py
hub/core/tests/test_compute.py
hub/integrations/pytorch/common.py
hub/integrations/pytorch/pytorch.py
hub/integrations/tests/test_pytorch_dataloader.py
hub/util/dataset.py

Allows to execute filter query on the dataset using functions
```python
ds.filter(lambda sample: sample.labels.numpy() == 2)
```
Or using simple query language:
```python
ds.filter('lables == 2')
```
Query language have following limitations:
* Scalar types are allowed: integers, float, boolean, strings
* Operations on the tensors that are result to a scalar _min_, _max_, _mean_, _shape_, _size_
* Tensor to scalar comparison is allowed, if and only if, tensor is size of 1, which can be mapped to the scalar.

[AL-1565] Filtering with simple query language

---

hub/core/chunk/base_chunk.py
hub/core/chunk/chunk_compressed_chunk.py
hub/core/chunk/sample_compressed_chunk.py
hub/core/chunk/test_chunk_compressed.py
hub/core/chunk/test_sample_compressed.py
hub/core/chunk/test_uncompressed.py
hub/core/chunk/uncompressed_chunk.py
hub/core/chunk_engine.py
hub/core/dataset/dataset.py
hub/core/meta/encode/tile.py
hub/core/serialize.py
hub/core/test_serialize.py
hub/core/tiling/deserialize.py
hub/core/tiling/optimizer.py
hub/core/tiling/sample_tiles.py
hub/core/tiling/serialize.py
hub/core/tiling/test_optimizer.py
hub/core/tiling/test_serialize.py
hub/core/tiling/util.py
hub/util/compression.py
hub/util/version_control.py

[AL-1587] Fix iteration slowdowns and import issue

---

hub/core/dataset/dataset.py
hub/core/version_control/test_version_control.py
hub/util/diff.py

Adds:-
`ds.branches` - returns a list of all branches of the dataset
`ds.commits` - returns a list of dictionaries, each containing all info about a particular commit (commit_id, commit_message, username and time), in order for the current branch.
`ds.diff(a,b,as_dict=True)` - returns dicts containing diffs instead of printing it.
`ds.get_commit_details(commit_id)` - returns a dict with all the details for a particular commit_id (commit_message, username and time)
Need to add tests

[AL-1598] Added more APIs for VC

---

hub/util/bugout_reporter.py
hub/util/bugout_token.py

moved bugout token to a file for better CD support
moved bugout token to a file for better CD support

moved bugout token to a file for better CD support

---

hub/core/dataset/dataset.py
hub/core/version_control/test_version_control.py
hub/util/version_control.py

A bug with info not persisting across versions was found in https://github.com/activeloopai/Hub/issues/1355.
This PR fixes the issue.

Fix info not getting updated across versions

---

hub/core/dataset/dataset.py
hub/util/version_control.py

Makes commits and checkout to new branches faster

Reduces flushes during commit/checkout

---

hub/__init__.py
hub/compression.py
hub/core/dataset/dataset.py
hub/core/tensor.py
hub/core/transform/transform.py
hub/htype.py

Adds/improves documentation for the following:-
1. Tensor .tobytes
2. New htypes (audio, text, json, list)
3. hub.delete
4. Dataset .pytorch
5. .eval in .compose and .compute

[AL-1331] Api reference updates

---

hub/core/chunk_engine.py
hub/core/dataset/dataset.py
hub/core/meta/encode/chunk_id.py
hub/core/transform/test_transform.py
hub/core/transform/transform.py
hub/core/version_control/commit_diff.py
hub/core/version_control/test_version_control.py
hub/util/diff.py
hub/util/encoder.py
hub/util/transform.py

Compresses data_added in diff, to take up less storage by only storing first and last index added instead of full set.
The format of the dicts returned in diff has also been changed:-
```
{
"image": {"data_added": [3, 6], "data_updated": {0, 2}, "created": False, "info_updated": False, "data_transformed_in_place": False},
"label": {"data_added": [0, 3], "data_updated": {}, "created": True, "info_updated": False, "data_transformed_in_place": False},
"other/stuff" : {data_added: [3, 3], data_updated: {1, 2}, created: True, "info_updated": False, "data_transformed_in_place": False}
}
```
Here the data_adeded is a range of sample indexes that were added to the tensor.
For example [3, 6] means that sample 3, 4 and 5 were added.
Another example [3, 3] means that no samples were added as the …

Compresses Diff format and fix diff bug in Transforms

---

hub/core/dataset/dataset.py
hub/core/transform/test_transform.py
hub/core/transform/transform.py
hub/core/version_control/commit_node.py
hub/core/version_control/test_version_control.py
hub/util/chunk_paths.py
hub/util/version_control.py

Changes the behaviour of version control commands to return git like commit ids.
ds.commit_id will now return the id of the last commit that was made rather than the next commit id that will be made.
A similar change has been made to checkout, to return the last commit made rather than the commit id of the new branch.

[AL-1592] Changes version control outputs

---

hub/requirements/common.txt

removing hub_shm since it is no longer required
https://github.com/activeloopai/Hub/search?q=shm returns nothing
removing hub_shm since it is no longer required

removing hub_shm since it is no longer required

---

hub/core/transform/transform.py
hub/util/transform.py

- Functions decorated with @hub.compute will now show proper IntelliSense while using .eval()
- Changed class name from TransformFunction to ComputeFunction

Enable intellisense for hub compute functions

---

hub/core/compression.py

Fix RCE in video decompression

---

hub/api/tests/test_api_tiling.py
hub/core/chunk/base_chunk.py
hub/core/compression.py
hub/core/io.py
hub/core/tiling/deserialize.py
hub/integrations/tests/test_pytorch.py

Fix tiling + pytorch

---

hub/api/tests/test_api_tiling.py
hub/core/meta/encode/tile.py

Slightly changes tile encoder storage format to use little endian ordering to be consistent with other encoders.
The version string is also now added to the bytes at the start

Tweak tile encoder format

---

hub/core/compression.py

Replace r_frame_rate with avg_frame_rate
Fixes #1433

Fix wrong video shape

---

hub/client/client.py

Changed auth token request method to POST

---

hub/core/chunk_engine.py
hub/core/tensor.py
hub/core/version_control/commit_chunk_set.py
hub/util/version_control.py

Closes #1456 
New commits were created without a CommitChunkSet (until any new data was added), leading to repeated key misses that slow down iteration. If any data was added to the commit, this wasn't a problem.
This PR changes the logic to create a new empty CommitChunkSet every time a new commit/branch is created, to avoid these repeated key misses. It also tries to fix existing datasets that don't have a CommitChunkSet in any of their commits by adding it (if write access is available).

Fix repeated key misses slowing down Version Controlled datasets

---

hub/__init__.py
hub/integrations/huggingface/__init__.py
hub/integrations/huggingface/huggingface.py
hub/integrations/tests/test_huggingface.py

Rename `from_huggingface` to `ingest_huggingface`

Rename from_huggingface to ingest_huggingface

---

hub/api/read.py

[AL-1637] Update hub.read docstring

---

hub/core/dataset/dataset.py
hub/util/warnings.py

[AL-1671] Dataset locks: always warn

---

hub/tests/path_fixtures.py

Delete hub cloud datasets properly in tests

---

hub/core/fast_forwarding.py

Update fast forwarding warning

---

hub/core/io.py

- Can't add unit test for this as it only happens for old datasets that don't have chunk sets created.

[Bug fix] Pytorch + old read only datasets

---

hub/api/tests/test_api.py
hub/tests/storage_fixtures.py

Remote URL read test fix: Do not test with s3 & gcs if options not enabled

---

setup.py

setup.py fix

---

hub/core/query/filter.py
hub/core/query/test/test_query.py

Fix hub compute + filter

---

hub/api/tests/test_insertion_out_of_order.py
hub/constants.py
hub/core/chunk_engine.py
hub/core/compression.py
hub/core/tensor.py
hub/util/casting.py

- Adds the ability to setitem to a random index which lies beyond current tensor length
- Fixes a bug with empty strings + lz4 compression
Usage:-
If label tensor has 5 samples and we want to insert sample at index 10.
```python
ds.label[10] = 2  # this fails
hub.constants._ENABLE_RANDOM_ASSIGNMENT = True
ds.label[10] = 2 # works now
```

[AL-1677] Allow out of order data insertion (recommended for internal use only, will greatly impact performace if used incorrectly)

---

hub/api/info.py
hub/api/tests/test_info.py

[Bug Fix] Fixes an issue with info not being updated properly outside with context

---

hub/api/tests/test_update_samples.py
hub/core/meta/encode/base_encoder.py

BytePositionsEncoder fix

---

hub/core/chunk_engine.py

[Bug] Fix memory leak

---

hub/api/tests/test_api.py
hub/core/dataset/dataset.py
hub/core/meta/dataset_meta.py
hub/core/meta/tensor_meta.py
hub/htype.py

`ds.create_tensor(tensor_name, hidden=True)` to create hidden tensors.

[AL-1698 (partial)] Hidden tensors

---

hub/integrations/__init__.py
hub/integrations/tf/__init__.py
hub/integrations/tf/datasettotensorflow.py
hub/integrations/tf/hubtensorflowdataset.py
setup.cfg

AL-[1616] Tensorflow API Design

---

hub/core/dataset/dataset.py
hub/core/version_control/test_version_control.py
hub/util/exceptions.py

AL-[1706] throw exception it commiting unchanged dataset

---

hub/integrations/tf/datasettotensorflow.py

Fix TF requirement when installing hub

---

README.md

Updated formatting of features in readme

---

hub/core/storage/s3.py
hub/requirements/common.txt

AL-[1714] Add ResponseStreamingError to list of retry exceptions

---

hub/__init__.py
hub/api/dataset.py
hub/api/tests/test_api.py
hub/core/dataset/dataset.py
hub/core/dataset/hub_cloud_dataset.py
hub/core/storage/gcs.py
hub/core/storage/local.py
hub/core/storage/s3.py
hub/util/exceptions.py

Make rename and copy show up in docs.
Add examples for dataset renames.
Check if new path is empty while renaming datasets.

Update dataset rename + api ref updates

---

README.md

fixed some hyperlinks and added the mention of 100+ datasets we've just hit!

added mention for 100+ datasets & fixes

---

hub/core/chunk/base_chunk.py
hub/core/chunk/chunk_compressed_chunk.py
hub/core/chunk/sample_compressed_chunk.py
hub/core/chunk/uncompressed_chunk.py
hub/core/chunk_engine.py
hub/core/dataset/dataset.py
hub/core/io.py
hub/core/tiling/deserialize.py
hub/integrations/pytorch/dataset.py
hub/integrations/pytorch/pytorch.py
hub/integrations/tests/test_pytorch.py
hub/integrations/tests/test_tensorflow.py
hub/integrations/tf/datasettotensorflow.py

```python
ds.pytorch(tobytes=True)   # all tensors return samples as bytes during iteration
ds.pytorch(tobytes=["x", "y"])  # specified tensors return samples as bytes during iteration
```

[AL-1724] tobytes for Pytorch & Tensorflow

---

hub/api/tests/test_api.py
hub/core/dataset/dataset.py

Allow creating branch even if dataset is locked by another user.

[AL-1710] Allow branch creation when dataset is locked

---

hub/api/tests/test_api.py
hub/core/dataset/dataset.py
hub/core/tensor.py
hub/util/pretty_print.py

Pretty printing should be done only when `ds.summary()` or `tensor.summary()` is called

Move pretty printing from __str__ to summary()

---

hub/core/fast_forwarding.py
hub/core/meta/tensor_meta.py

[AL-1766] hub.copy fix (2) + small refac

---

hub/api/tests/test_api.py
hub/api/tests/test_api_with_compression.py
hub/core/chunk_engine.py
hub/core/serialize.py
hub/htype.py
hub/util/image.py

Added new htypes `image.rgb` and `image.gray`

[AL-1749] image.rgb and image.gray htypes

---

hub/api/tests/test_api_with_compression.py
hub/core/chunk_engine.py
hub/util/image.py

Fix case when recompressing image with `image.rgb` or `image.gray` htypes.

[BUG] Image htypes fix for recompression

---

hub/api/tests/test_rechunk.py

While running pytest to check if unit tests pass, a dataset is being created locally every time `test_rechunk_3` in `test_rechunk.py` was run. This PR uses `CliRunner().isolated_filesystem()` to make sure those local files are deleted after the test passes.

[small] Remove files created during test_rechunk

---

hub/core/dataset/dataset.py
hub/core/io.py
hub/integrations/pytorch/dataset.py
hub/integrations/pytorch/pytorch.py
hub/integrations/tests/test_pytorch.py

Adds return_index argument to ds.pytorch, which returns indexes. This is useful when working with shuffled data.
Usage:-
```python
ds = hub.dataset("path/to/some/dataset")
dl = ds.pytorch(shuffle=True, return_index=True, batch_size=4)
for batch in dl:
pass
```

[AL-1790] Adds ability to return indexes in pytorch

---

hub/api/tests/test_api.py
hub/core/dataset/dataset.py

Prevent updating `tensor.info.class_names` from changing `HTYPE_CONFIGURATIONS`

[BUG] Prevent changing htype config when updating class_names

---

hub/api/tests/test_api.py
hub/core/tensor.py
hub/util/numeric_to_text.py

tensor.data() for htype class labels returns a dictionary containing 2 keys, "numeric" which has the same value as .numpy() and text which is converted into text class labels if class labels are present, otherwise key is skipped.

[AL-1795] Changes .data to return both numeric and text value for class labels

---

hub/core/sample.py

Just changed the way of passing credentials to the `GCSProvider`, to be like it is done in the `storage_provider_from_path` method.

Correctly passing credentials to gcp provider

---

hub/api/tests/test_api.py
hub/core/sample.py
hub/core/tensor.py

Fixed `tensor.tobytes` for linked tensors

[BUG] Fix tobytes for linked tensors

---

hub/api/tests/test_api.py
hub/api/tests/test_update_samples.py
hub/core/tensor.py

When the value in setitem is a single sample, in some cases it was being treated as a list of samples, leading to loss of dimensionality when appending, which caused errors

[BUG] Fix setitem issue with list of length 1

---

hub/visualizer/tests/test_playback.py

Skip video playback test for windows python 3.6

Fix linked video playback test

---

hub/core/chunk_engine.py

Does partial reads to only get header while reading shapes instead of getting full chunks to speed up shape retrieval in cases where a shape encoder doesn't exist.

[AL-1806] Do partial reads to retrieve shape for samples

---

hub/integrations/pytorch/shuffle_buffer.py

Directly access tensor.element_size() instead of using tensor.storage.element_size() which is slower

[Optimization] Make sample size calculation faster in pytorch

---

hub/core/dataset/dataset.py
hub/core/query/test/test_query.py
hub/core/tensor.py

`list(view.sample_indices)` returns the indices of samples in a view.
Can create view unions like this:
```
view1 = ds[:10]
view2 = ds[5:15]
union = ds[sorted(list(set(view1.sample_indices).union(view2.sample_indices)))]
```

[AL-1820] view.sample_indices

---

hub/api/tests/test_api.py

Skip test_hub_remote_read_gdrive_root test if --gdrive flag not specified

Skip google drive root test if  no --gdrive flag

---

hub/core/tiling/sample_tiles.py
hub/integrations/pytorch/shuffle_buffer.py

Displays a progress bar while pytorch shuffle buffer is getting filled

[AL-1748] Show a progress bar while pytorch shuffle buffer is getting filled

---

hub/client/config.py

- [X ]  [My code follows the style guidelines of this project](https://www.notion.so/activeloop/Engineering-Guidelines-d6e502306d0e4133a8ca507516d1baab) and the [Contributing document](https://github.com/activeloopai/Hub/blob/release/2.0/CONTRIBUTING.md)
- [X ]  I have commented my code, particularly in hard-to-understand areas
- [X ]  I have kept the `coverage-rate` up
- [X ]  I have performed a self-review of my own code and resolved any problems
- [X ]  I have described and made corresponding changes to the relevant documentation
- [ X]  New and existing unit tests pass locally with my changes
As we have updated the location of dev to https://app-dev.activeloop.dev, we need to update this in the hub client configuration.  We are setting  HUB_REST_ENDPOINT_DEV = …

Changed dev location to https://app-dev.activeloop.dev/

---

hub/api/tests/test_pop.py
hub/core/dataset/dataset.py

Adds ds.pop method to Dataset to pop from multiple tensors at once instead of popping from each tensor one by one

Adds ability to pop sample from dataset instead of popping from individual tensors

---

hub/core/dataset/dataset.py
hub/core/query/test/test_query.py

Fix double indexing when saving strided views

---

hub/api/tests/test_api.py
hub/core/transform/transform.py
hub/util/casting.py

Fix get_incompatible_dtype bug

---

hub/api/tests/test_link.py
hub/core/link_creds.py

- None/"ENV" is no longer added to used_creds_keys for linked data

[Bug fix] Ensure None/"ENV" isn't added to used_creds_keys for linked data

---

hub/api/tests/test_insertion_out_of_order.py
hub/api/tests/test_link.py
hub/api/tests/test_pop.py
hub/api/tests/test_rechunk.py
hub/core/chunk/base_chunk.py
hub/core/link_creds.py
hub/core/linked_sample.py
hub/core/transform/test_transform.py
hub/util/htype.py
hub/util/link.py

- Raises ValueError when generic htypes are used with links. So now, htype= "link' or "sequence[link]" or "link[sequence]" are no longer allowed.
- Raises a more informative error if user tries to append hub.link sample to a tensor that isn't a link.

[AL-1912] Don't allow generic htypes with link

---

hub/core/storage/local.py
hub/core/version_control/test_version_control.py

[DL-684] Fix ds.reset bug with local datasets

---

hub/core/serialize.py

Ensure that new format for chunk id isn't used for encoders with version <= 2.7.6

---

hub/api/tests/test_api.py
hub/client/client.py

Fixed bug related to raising UserNotLoggedInException when public user tries to access the public path that does not exists

[Bugfix] 1828 raising UserNotLoggedInException when invalid path is provided

---

hub/api/tests/test_api.py
hub/core/dataset/dataset.py
hub/experimental/dataloader.py
hub/experimental/test_pytorch.py
hub/remove_tensor.py
hub/util/exceptions.py

Added Error message that is thrown when user tries to append a sample and does not provide the the name of the tensor.

[DL-650] Better error handling when not passing a tensor name to ds.append

---

deeplake/core/dataset/dataset.py
deeplake/integrations/tf/datasettotensorflow.py

As described in #1885  iterating a small dataset with `ds.tensorflow()` is very slow.
If using the tensorflow dataset on a hub dataset which consist of multiple samples with small size, the iteration becomes considerably faster if using fetch_chunks=True when getting the data. This commit adds the ability to pass that option when creating the tensorflow dataset from the hub dataset.
On an MNIST dataset the result is 25 times faster iteration.
Benchmark can be found here:
https://gist.github.com/daniel-falk/188b96013e9f0cedcf555a0a30fa177d
TF chunks: 957 frames / second
TF current: 26 frames / second
Hub chunks: 1294 frames / second
Hub per sample: 28 frames / second

Allow tensorflow dataset to fetch chunks

---

deeplake/core/dataset/dataset.py
deeplake/core/lock.py

Lock file was being written by the previous machine when a dataset is overwritten by another machine.

[DL-763] Locking fix

---

deeplake/client/client.py
deeplake/util/storage.py

Region returned from backend wasn't being used while creating s3 provider

Fix region issue with activeloop storage datasets

---

deeplake/core/compression.py

When calling 
```
deeplake.read("sample.wav", verify=True, compression="wav")
```
current code breaks as `_read_audio_shape` Is called with two arguments. 
Not sure why "compression" argument was passed - perhaps API changed at some point

fix read for wav compressed audio

---

deeplake/core/dataset/dataset.py
deeplake/core/transform/test_transform.py
deeplake/util/version_control.py

The problem:-
- Dataset info object was being cleared from cache but not from dataset object, so changes were being made only to the in memory object and didn't persist in the actual storage.
The solution:-
- Reference to info and dataset diff are cleared from dataset object when cleared from cache. 
- On using these objects they are added back to the cache and are properly tracked.

[AL-1999] [Bug fix] lnfo not being updated after using Deep Lake compute on dataset.

---

deeplake/api/tests/test_api.py
deeplake/core/dataset/dataset.py
deeplake/core/meta/dataset_meta.py
deeplake/core/transform/transform.py
deeplake/util/version_control.py

- prefix temporary tensors with `__temp`
- such tensors will be discarded (if they were not removed) during the next dataset load
- prevents dataset corruption

[DL-782] Delete temp tensors in case append fails during transforms

---

deeplake/experimental/test_pytorch.py
deeplake/integrations/pytorch/common.py
deeplake/integrations/pytorch/dataset.py

[CUS-32] Fix dataloader behaviour for json and list tensors

---

deeplake/core/dataset/dataset.py
deeplake/core/storage/s3.py
deeplake/enterprise/dataloader.py
deeplake/enterprise/util.py
deeplake/integrations/tf/datasettotensorflow.py
deeplake/util/exceptions.py
deeplake/util/keys.py

If e.g. the wrong AWS profile is used the download of the open datasets which are stored in S3 will fail. These errors was completely hidden and was instead displayed as if the dataset does not exists, e.g.:
```
hub.util.exceptions.DatasetHandlerError: A Hub dataset does not exist at the given path (hub://activeloop/mnist-train). Check the path provided or in case you want to create a new dataset, use hub.empty().
```
This commit creates a new excpetion type which is not excepted to make it clear that it is an AWS S3 access error that is the cause.
This commit makes the error messages more useful for debugging. E.g, consider a user who has a default region setup for AWS:
```
#~/.aws/config
[default]
region: eu-north-1
```
When the user wants to try out hub they do:
```bash
python -c …
```

Do not hide S3 access errors

---

deeplake/core/transform/test_transform.py
deeplake/core/transform/transform.py
deeplake/util/transform.py

Since these can be used to iterate a dataset with paralization in an easy way.
See https://github.com/activeloopai/deeplake/issues/2002

Allow the use of compute functions on read-only datasets

---

deeplake/api/dataset.py
deeplake/api/tests/test_api.py
deeplake/tests/common.py
deeplake/util/exceptions.py
deeplake/util/path.py

- Only letters, numbers, hyphens and underscores are allowed in cloud dataset names
- Local dataset names can have spaces in addition

[CUS-56] Restrict characters in dataset names

---

deeplake/api/dataset.py
deeplake/api/tests/test_connect_datasets.py
deeplake/core/dataset/dataset.py
deeplake/util/connect_dataset.py

Added `token` parameter examples in docstrings.
The idea is for `ds.connect` to modify the underlying dataset object and convert it to a `DeepLakeCloudDataset` so that all the features, like managed creds keys, are accessible immediately without the need to reload the dataset.

[CUS-57] [CUS-58] In place ds connect

---

deeplake/core/io.py
deeplake/enterprise/dataloader.py
deeplake/enterprise/test_pytorch.py
deeplake/integrations/pytorch/dataset.py
deeplake/integrations/pytorch/pytorch.py
deeplake/integrations/tests/test_pytorch.py

ds.group.pytorch or ds['group'].pytorch() should return tensor names without the group name in front

[DL-805] Groups + Loader fixes

---

deeplake/api/tests/test_api.py
deeplake/integrations/pytorch/shuffle_buffer.py
deeplake/integrations/tests/test_pytorch.py

[BUGFIX] Fix PIL decode method with multiple workers and shuffling

---

deeplake/api/tests/test_api.py
deeplake/api/tests/test_rechunk.py
deeplake/core/chunk/base_chunk.py
deeplake/core/dataset/dataset.py
deeplake/core/serialize.py
deeplake/core/storage/google_drive.py
deeplake/core/tensor.py
deeplake/core/transform/test_transform.py
deeplake/core/transform/transform.py
deeplake/util/check_rechunk.py
deeplake/util/class_label.py
deeplake/util/encoder.py
deeplake/util/transform.py

- Automatically rechunk uncompressed tensors at end of transform if average chunk size is too low

[AL-2077] Automatically rechunk at end of transform

---

deeplake/api/tests/test_nifti.py
deeplake/core/linked_sample.py
deeplake/tests/storage_fixtures.py

- Use our S3 for nifti cloud test instead of the http link because sometimes it times out

[AL-2094] Switch to S3 link for nifti cloud test

---

deeplake/enterprise/dataloader.py

Add attributes to dataloader to make it more consistent with Pytorch loader

---

deeplake/core/dataset/dataset.py

The flag `skip_ok` was lost in the `Dataset.extend` call which prevented extending some tensors of a dataset.

Fix skip_ok in Dataset.extend

---

deeplake/api/tests/test_downsample.py
deeplake/core/tensor_link.py
deeplake/enterprise/dataloader.py
deeplake/util/downsample.py

Handle images with 0 in shape and grayscale images with shape (h,w,1) in downsampling

---

deeplake/api/tests/test_views.py
deeplake/core/dataset/dataset.py
deeplake/core/dataset/deeplake_cloud_dataset.py

- Remove support for saving views when user is not part of the dataset's org.
- No more saving views in user queries dataset.
- If user is not part of dataset's org, they can only save the view in a custom specified location.

[AL-2129] Deprecate saving views when user is not in dataset's org

---

deeplake/api/tests/test_api.py
deeplake/api/tests/test_views.py
deeplake/core/chunk_engine.py
deeplake/core/tensor.py

- Fix materialization of views with empty tensor
- Fix copying empty tensors: `ds.abc.extend(ds.xyz)` when ds.xyz is full of empty samples

[CUS-95] Fix materialization of views with empty tensors

---

deeplake/api/tests/test_link.py
deeplake/core/tensor_link.py
deeplake/tests/path_fixtures.py

Fixes issues with linked tensors when working with datasets containing both rgb and grayscale images

---

deeplake/api/tests/test_views.py
deeplake/core/dataset/dataset.py
deeplake/core/dataset/view_entry.py
deeplake/core/storage/gcs.py
deeplake/core/storage/local.py
deeplake/core/storage/s3.py
deeplake/core/tests/test_locking.py

- Currently, VDS is loaded in write mode whenever possible. It should have same write mode as parent.

Load VDS in same read_only mode as parent 

---

deeplake/api/tests/test_rechunk.py
deeplake/constants.py
deeplake/core/chunk_engine.py
deeplake/core/dataset/dataset.py
deeplake/core/storage/google_drive.py
deeplake/core/tests/test_locking.py
deeplake/core/transform/test_transform.py
deeplake/core/transform/transform.py
deeplake/util/transform.py

- Automatically rechunk uncompressed tensors at the end of transform

Automatically rechunk uncompressed tensors at the end of transform

---

deeplake/api/tests/test_api.py
deeplake/core/dataset/dataset.py

--Temporarily disabling summary for views, because it does not work properly in some cases

Disabling summary for views

---

deeplake/core/dataset/dataset.py

fix: hash_id catch wrong type.

---

deeplake/api/tests/test_api_with_compression.py
deeplake/api/tests/test_grayscale.py
deeplake/api/tests/test_update_samples.py
deeplake/core/chunk/base_chunk.py
deeplake/core/chunk_engine.py
deeplake/core/compression.py
deeplake/core/transform/test_transform.py

* Images are always 3d, even if first sample is 2d.

[AL-2229] Images always 3D

---

deeplake/api/tests/test_api.py
deeplake/core/chunk_engine.py

- Fix wrong data returned from sequences when number of samples (after flattening) is a multiple of tensor length

[AL-2212] Fix wrong data returned in sequences

---

deeplake/core/dataset/dataset.py
deeplake/core/storage/s3.py

nest_asyncio.apply() fails in certain environments with streamlit. Related thread https://github.com/streamlit/streamlit/issues/744

Catch all exceptions when initializing async libraries

---

deeplake/api/tests/test_api.py
deeplake/htype.py

** Added ability to specify `keypoints` and `connections` .info when creating a keypoints coco tensor

[AL-2137] Added optional inputs to kp coco

---

deeplake/core/dataset/dataset.py

* Get org_id for local datasets from "ACTIVELOOP_HUB_USERNAME" environment variable.

Set org_id for local datasets if environment variable is set

---

deeplake/core/transform/test_transform.py
deeplake/core/transform/transform.py
deeplake/util/exceptions.py
deeplake/util/transform.py

- AllSamplesSkippedError if all samples were skipped in a transform by `ignore_errors` param
- Bugfix for when a bad sample is at the end of transform, samples doesn't get flushed

[AL-2270] Transforms - Error if all samples are skipped +bugfixes

---

deeplake/enterprise/test_pytorch.py
deeplake/integrations/pytorch/shuffle_buffer.py
deeplake/requirements/tests.txt
deeplake/tests/common.py

corrected tensor calculation logic

---

deeplake/core/dataset/dataset.py
deeplake/core/transform/test_transform.py
deeplake/core/transform/transform_dataset.py
deeplake/core/transform/transform_tensor.py
deeplake/util/class_label.py

- Use `ds.append(..., append_empty=True)` to append empty samples to unspecified tensors in transforms

[AL-2278] append_empty option in transforms

---

deeplake/api/tests/test_api.py
deeplake/core/dataset/dataset.py

- Pass iteration flag to groups

[AL-2280] Fix numpy slowdown with iteration and groups

---

deeplake/core/transform/test_transform.py
deeplake/core/transform/transform.py
deeplake/core/transform/transform_dataset.py
deeplake/util/transform.py

- Produce useable datasets in transforms even in case of errors.
- Ordering of samples will not be correct if multiple workers are used (therefore non-resumable) but this state will be better than an unusable dataset

[AL-2277] Avoid producing corrupt datasets in transforms

---

deeplake/core/dataset/dataset.py

fix issue with ds.connect

---

deeplake/core/dataset/deeplake_query_tensor.py

Fixed .tensors print for indra ds wrapper.

---

deeplake/util/spinner.py

Setting `deeplake.constants.SPINNER_ENABLED = False` disables spinner.

[AL-2302] Fix issue with SPINNER_ENABLED const

---

deeplake/api/tests/test_none.py
deeplake/core/chunk_engine.py
deeplake/util/casting.py

[AL-2298] Fix bugs with None samples

---

deeplake/api/dataset.py
deeplake/api/tests/test_api.py
deeplake/core/dataset/deeplake_cloud_dataset.py

added missing `ds_name` field
There is a specific case in which I `deeplake.empty` is called and a cloud dataset path is passed. In that case a function called [`_is_sub_ds`](https://github.com/activeloopai/deeplake/blob/2bfa3a2a0617e63baf6343dbd61148c926dc0561/deeplake/core/dataset/deeplake_cloud_dataset.py#L76) is used to check if we have a sub directory dataset, since `ds_name` was not set the code was failing. 
To reproduce
```python
from deeplake.constants import MB
import numpy as np 
import deeplake
dataset_path = f"hub://<YOUR_ORG_ID>/<YOUR_DS_NAME>"
ds = deeplake.empty(
path=dataset_path,
runtime={"db_engine": True},
token=<TOKE>,
overwrite=True,
org_id=<YOUR_ORG_ID>,
)
```
Resulting in the follow error
```
Traceback (most recent call last):
File …
```

Added ds_name into deeplake_cloud_dataset.py

---

README.md
deeplake/api/dataset.py
deeplake/api/tests/test_api.py
deeplake/core/dataset/deeplake_cloud_dataset.py
deeplake/core/link_creds.py
deeplake/util/spinner.py

[AL-2308] check linked creds expiration

---

deeplake/api/tests/test_rechunk.py
deeplake/core/chunk_engine.py

- Fix serialization of sample in rechunk for text, json and list htypes

[AL-2303] Rechunk fix for JSON

---

deeplake/core/vectorstore/deeplake_vectorstore.py
deeplake/core/vectorstore/test_deeplake_vectorstore.py
deeplake/core/vectorstore/vector_search/dataset/dataset.py
deeplake/core/vectorstore/vector_search/utils.py

VectorStore bug fix

---

deeplake/core/vectorstore/test_deeplake_vectorstore.py
deeplake/core/vectorstore/vector_search/dataset/dataset.py
deeplake/core/vectorstore/vector_search/dataset/test_dataset.py

Added backwards compatibility for add method

VectorStore ids backwards compatibility

---

deeplake/__init__.py

- Remove bugout exception hooks from init

[Tiny] Removed exception hooks

---

.gitignore
deeplake/core/dataset/dataset.py
deeplake/util/keys.py
deeplake/util/tests/test_keys.py

Currently, if a single file is missing in a dataset folder (`dataset_meta.json`), Deep Lake thinks it’s not a deeplake dataset leading to a confusing error of `….."A Deep Lake dataset does not exist at the given path….."`. 
This make this check more sophisticated, making "the is this a dataset directory" check look for a variety of files while also adding a "validation" function for times when any of them missing will be a problem.

[AL-2322] Improved dataset directory validation

---

deeplake/core/vectorstore/vector_search/indra/search_algorithm.py

Without libdeeplake (indra) installed, for example on Windows, vector search causes exception when exec_option is "tensor_db"
Traceback of exception without this fix:
```
Traceback (most recent call last):
File "C:\Program Files\Python310\lib\contextlib.py", line 153, in __exit__
self.gen.throw(typ, value, traceback)
File "E:\venv\lib\site-packages\llama_index\callbacks\base.py", line 133, in as_trace
yield
File "E:\venv\lib\site-packages\llama_index\indices\query\base.py", line 23, in query
response = self._query(str_or_query_bundle)
File "E:\venv\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 147, in _query
nodes = self.retrieve(query_bundle)
File "E:\venv\lib\site-packages\llama_index\query_engine\retriever_query_engine.py", line 107, in retrieve
nodes = …
```

Fixed vector search with tensor_db exec_option without indra installed

---

deeplake/api/dataset.py
deeplake/api/tests/test_api.py
deeplake/api/tests/test_link.py
deeplake/api/tests/test_video.py
deeplake/core/chunk_engine.py
deeplake/core/dataset/dataset.py
deeplake/core/vectorstore/test_deeplake_vectorstore.py
deeplake/core/vectorstore/vector_search/dataset/dataset.py
deeplake/core/vectorstore/vector_search/dataset/test_dataset.py
deeplake/core/vectorstore/vector_search/indra/query.py
deeplake/enterprise/test_tensorflow.py
deeplake/util/connect_dataset.py
deeplake/visualizer/tests/test_playback.py

Working through "bug" and "code smell" sections of the sonar report. 
The one "bug" was  `test_delete_and_commit()` missing an assert
The rest were "code smells":
- Variables in tests that were unneeded to set
- Functions that define input/output types as something like `str` but are passed or return None, so I added Optional to type
- Switched `f""` strings to regular strings if there was no substitution   
- Don't use insecure http urls (this was in the security section)
Should not change functionality, just clean up code
Nothing

Addressing Sonar-found bugs and code smells.

---

deeplake/api/tests/test_views.py
deeplake/core/dataset/dataset.py
deeplake/core/vectorstore/vector_search/indra/search_algorithm.py
deeplake/util/transform.py

- Specifying `ignore_errors=True` in `ds.save_view` will skip any samples that cause errors.
- Applicable only when `optimize=True` and in the presence of linked tensors.
- Normal tensors cannot cause similar errors and does not need `ignore_errors`.

[AL-2358] ignore_errors argument for ds.save_view

---

deeplake/core/transform/test_transform.py
deeplake/core/transform/transform.py
deeplake/util/transform.py

- This PR prints a summary at the end of a transform if `ignore_errors=True`
- It will look as such:
```
No. of samples successfully processed: 16 (80.0%)
No. of samples skipped: 4 (20.0%)
```

[AL-2351] Print a transform summary if ignore_errors=True

---

deeplake/core/dataset/deeplake_query_tensor.py
deeplake/core/tests/test_deeplake_indra_dataset.py
deeplake/core/vectorstore/test_deeplake_vectorstore.py
deeplake/enterprise/convert_to_libdeeplake.py
setup.py

if the dataset's token is empty or None and the dataset is not a public one then we need to get the token from the client side to normally process and create dataloader object from it

[AL-2372] do not accept empty tokens for private datasets

---

deeplake/core/dataset/dataset.py

Extending with a numpy array of indices is much faster.

[AL-2368] Optimization for saving shallow views

---

deeplake/core/tests/test_deeplake_indra_dataset.py
deeplake/enterprise/convert_to_libdeeplake.py

fix ternary operator

---

deeplake/core/dataset/dataset.py
deeplake/enterprise/libdeeplake_query.py

If the indra dataset is already exists we are trying to use already in memory indra dataset instead of creating new one

Reuse indra dataset in query.

---

deeplake/core/dataset/dataset.py
deeplake/core/dataset/deeplake_cloud_dataset.py
deeplake/core/version_control/test_version_control.py
deeplake/util/version_control.py

Creates a new `ds.delete_branch(branch_name)` function which deletes the given branch name.
You cannot delete branches:
- You are currently on
- The main branch,
- Non-leaf branches
- That have been previously merged into another branch
- Simplified the requirements down to only "simple" branches to avoid complex history-rewriting 
- It locks the version_control_info.json and the branches to delete before operating
- It takes CommitMaps referencing a branch's commits into account
Is there complex version histories this doesn't handle correctly?

[AL-2360] Added dataset.delete_branch() feature

---

deeplake/util/transform.py

- When compute functions are really fast, progress bar updates become the slowest part of the chain.
- Update it in intervals of 5 seconds.

[AL-2353] Add delay for transform progress bar updates

---

deeplake/util/version_control.py

Fixes type annotation to avoid this error:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/s/work/deeplake/deeplake/__init__.py", line 19, in <module>
from .api.dataset import dataset as api_dataset
File "/Users/s/work/deeplake/deeplake/api/dataset.py", line 9, in <module>
from deeplake.auto.unstructured.image_classification import ImageClassification
File "/Users/s/work/deeplake/deeplake/auto/unstructured/image_classification.py", line 13, in <module>
from deeplake.core.dataset import Dataset
File "/Users/s/work/deeplake/deeplake/core/dataset/__init__.py", line 1, in <module>
from .dataset import Dataset  # type: ignore
File "/Users/s/work/deeplake/deeplake/core/dataset/dataset.py", line 22, in <module>
from deeplake.util.version_control import ( …
```

Fixed List[str] annotation in delete_branch feature

---

deeplake/core/dataset/dataset.py

Add progress bar to ds.extend

---

deeplake/core/vectorstore/test_deeplake_vectorstore.py
deeplake/core/vectorstore/vector_search/utils.py

There is a bug in auto casting vectorstore, most probably vector_db path changes, and now it is causing a lot of issues on LangChain side

Exec option autocasting fix

---

deeplake/core/dataset/dataset.py
deeplake/core/version_control/test_version_control.py
deeplake/util/version_control.py

Creates a new `dataset._squash_main()` method which squashes all the commits in main into a single commit. 
It moves the latest versions of the chunk files and other metadata files from the various existing commits up to the head commit (for now, FIRST_COMMIT_ID), updates the version_control_info.json file to no longer reference the old commits, and deletes the old version directories. The end result is a single commit with the message "Squashed commits" and a new staging version for future changes. 
It only supports squashing commits on the main branch, and only when there are no other branches and when there are no views.
This keeps the logic safer and simpler, and given that the reason for the feature right now is for people who had a bunch of commits auto-generated for them and they …

Added _squash_main() method

---

deeplake/core/vectorstore/deeplake_vectorstore.py
deeplake/core/vectorstore/test_deeplake_vectorstore.py
deeplake/core/vectorstore/vector_search/dataset/dataset.py

There were some users that didn't know what should they be putting inside of embed_data parameter ins Vectorstore's search method. Intuitively most of them expect it to support direct strings. In the future we are also planning to add batch query support. So decided to add make embed_data parameter accept both string and List of strings.

Set VectorStore.search embedding argument type

---

deeplake/core/storage/azure.py
deeplake/core/storage/tests/test_storage_provider.py

- There is a maximum limit of 256 on the number of blobs that can be deleted using a single `delete_blobs` request.
- So batch the blobs to be deleted.

Batched azure storage clear

---

.github/langchain-tests/test_activeloop_deeplake.py
deeplake/api/tests/test_api.py
deeplake/core/dataset/dataset.py

- `create_tensor` with htypes and `exist_ok` was not correctly comparing the configs of existing and new tensors.
- Closes #2548

Fix create_tensor(..., exist_ok=True) behavior with htypes

---

deeplake/core/seed.py
deeplake/core/tests/test_seed.py

#2537 introduced the ability to specify a seed for random algorithms used in Deeplake, but it caused a `TypeError` to be thrown in Python 3.9 and earlier due to difference in support in `isinstance(..., Optional[int])`
Works fine with 3.10+
Nothing

Fix support for deeplake.random.seed() on python 3.9 and earlier

---

deeplake/core/vectorstore/vector_search/dataset/dataset.py
deeplake/core/vectorstore/vector_search/dataset/test_dataset.py

There was a bug in vectorstore chunk_by_bites algorithms which caused an infinite loop. Fixed it.

Vector Srore Memory leak Fix

---

sonar-project.properties

The sonar reporting was counting test files in overall code to be covered by tests. This excludes test-related files from the coverage reporting.

Added sonar exclusions/inclusions for tests

---

.github/workflows/test-push.yml
setup.py

check indra availability

---

deeplake/core/seed.py
docs/source/Datasets.rst
docs/source/deeplake.random.rst
docs/source/index.rst

Updated deeplake.random.seed documentation

---

deeplake/api/tests/test_api.py
deeplake/core/vectorstore/test_deeplake_vectorstore.py
deeplake/htype.py

Set default embedding htype to float32

---

deeplake/constants.py
deeplake/enterprise/convert_to_libdeeplake.py

Cache size propagete to libdeeplake.

---

deeplake/util/path.py

`typing_extensions` should not be a dependency of deeplake, and no need to add it.
With the current code, unless a user manually installs typing_extensions, they get the error:
```
File ~/Documents/code/activeloop_index/deeplake/deeplake/util/path.py:5
2 import posixpath
3 from typing import Optional, Union, Tuple, Dict
----> 5 from typing_extensions import LiteralString
7 from deeplake.core.storage.provider import StorageProvider
8 from deeplake.util.tag import process_hub_path
ModuleNotFoundError: No module named 'typing_extensions'
```

Removed typing_extensions usage

---

deeplake/util/scheduling.py

Fixed virtual tensor test.

---

deeplake/constants.py
deeplake/core/tensor.py
deeplake/core/vectorstore/deeplake_vectorstore.py
deeplake/core/vectorstore/test_deeplake_vectorstore.py
deeplake/core/vectorstore/vector_search/indra/index.py
deeplake/core/vectorstore/vector_search/utils.py

-- Added index regeneration back. It was removed previously by mistake
-- Minor refactors to how parameters are passed
-- Increased M and efConstruction to provide more accuracy to index

Brought back index regeneration

---

deeplake/core/dataset/deeplake_query_dataset.py
deeplake/core/dataset/deeplake_query_tensor.py
deeplake/core/tests/test_deeplake_indra_dataset.py

Added sample_indices api to virtual tensors.

---

deeplake/core/compression.py

Switch to lz4 block.

---

deeplake/enterprise/util.py

change libdeeplake error message

---

deeplake/auto/structured/dataframe.py

-- Fixed minor bug when specifying custom column params in ingest dataframe

[BUGFIX] minor fix for parsing params in ingest_dataframe

---

deeplake/core/dataset/dataset.py
deeplake/core/dataset/deeplake_query_dataset.py
deeplake/core/vectorstore/deep_memory.py
deeplake/integrations/pytorch/pytorch.py
docs/source/Tensor-Query-Language.rst

No need to pip install deeplake[enterprise] anymore, so removed references to it.
Did a search in this repo for 'deeplake[enterprise]" . Is there other places that need to be changed that got missed?

Removed pip install deeplake[enterprise] references in docs

---

deeplake/api/tests/test_json.py
deeplake/api/tests/test_text.py
deeplake/core/tensor.py

- `.data()` should return empty list for `text` and `json` htypes.

Fix `.data()` for empty tensors

---

deeplake/api/tests/test_pickle.py
deeplake/core/chunk_engine.py

- Cached chunks should not be present in the serialized dataset
- Set these attributes to `None` in the `ChunkEngine` before returning the state in `__getstate__`

Remove cached chunks from dataset pickle

---

deeplake/api/tests/test_api.py
deeplake/util/pretty_print.py

- `np.dtype('float64')` compares equal to `None` so the summary was wrong.
- Compare with `is` instead.

Fix `ds.summary`

---

deeplake/core/vectorstore/test_deeplake_vectorstore.py

Currently there are 3 windows tests failing on main (fixing those by adding libdeeplake decorator):
```
deeplake/core/vectorstore/test_deeplake_vectorstore.py::test_update_embedding_row_ids_and_ids_specified_should_throw_exception - ImportError: High performance features require the libdeeplake package which is not available in Windows OS
deeplake/core/vectorstore/test_deeplake_vectorstore.py::test_update_embedding_row_ids_and_filter_specified_should_throw_exception - ImportError: High performance features require the libdeeplake package which is not available in Windows OS
deeplake/core/vectorstore/test_deeplake_vectorstore.py::test_vs_commit - ImportError: High performance features require the libdeeplake package which is not available in Windows OS

Fixing failing windows tests

---

deeplake/core/storage/s3.py

Use upload_fileobj to upload large data into s3.

Multipart upload for large data.

---

deeplake/core/vectorstore/deep_memory/deep_memory.py
deeplake/core/vectorstore/deep_memory/test_deepmemory.py
deeplake/core/vectorstore/deeplake_vectorstore.py
deeplake/util/exceptions.py

This PR will remove the references to Waitlist when checking the access to DeepMemory.
Currently, DeepMemory access will be automatically granted to anyone on a Paid Org plan. (Similar to now previously query access was granted)
Please note that some test cases might need to be adjusted accordingly.

Move from Waitlist concept in DeepMemory access

---

deeplake/core/storage/azure.py
deeplake/core/storage/gcs.py
deeplake/core/storage/local.py
deeplake/core/storage/s3.py
deeplake/util/transform.py

- The custom cached relpath function is not thread-safe so don't use it in parallel code paths.

Don't use cached relpath in parallel code

---

deeplake/core/vectorstore/deeplake_vectorstore.py

The not-yet-released PR #2735 removed `num_workers_from the argument list, but existing code such as the llama-index integration may pass it along still.
The argument would go into the kwargs and then confict/duplicate with our explicitly-set `num_workers=0` argument.
This PR removes the value from kwargs if set. 
Completes the work for #2735, the fix isn't needed for any existing deeplake releases.

Better handle when num_workers is passed to deeplake_vectorstore

---

deeplake/core/chunk/sample_compressed_chunk.py
deeplake/core/sample.py

When a new image is added and it does not fit in a sample compressed chunk, the filename gets lots from the sample_info.
This ensures the filename remains set on the Sample object for later use by the sample_info tensor
We had to remove the logic from sample.py that uses the path as the compressed data if it exists now that we're better setting the path. No tests are failing from the change, so it seems like a needed change to that code
Nothing

Ensure filename remains set for later saving in sample_info

---

deeplake/util/remove_cache.py

For code that goes through `get_dataset_with_zero_size_cache`, the lock_enabled and lock_timeout arguments are not passed along to the cloned dataset.
This PR fixes it so they are

Preserve lock settings in `get_dataset_with_zero_size_cache`

---

deeplake/client/client.py
deeplake/requirements/tests.txt

With updates to the auth work, I added an optimization for public token handling which will not work with the current production hub server code.
This PR reverts the code back to what was in main on the last release  
We can bring this change back after teh server-side changes have been made

Revert public token handling until future release

---

deeplake/core/dataset/deeplake_query_dataset.py

Fixed edge cases in indra dataset adaptor.

---

README.md

Update README to remove cli mention.

---

deeplake/enterprise/dataloader.py

fix upcasting logic

---

deeplake/api/dataset.py
deeplake/client/client.py
deeplake/client/test_client.py
deeplake/client/utils.py
deeplake/core/dataset/dataset.py
deeplake/core/vectorstore/dataset_handlers/dataset_handler_base.py
deeplake/core/vectorstore/vector_search/utils.py
deeplake/util/bugout_reporter.py

Now that the CLI has been deprecated there's no way to modify the api tokens saved to `~/.activeloop/token`. We have removed support for providing tokens in this file.
Users wanting to set an authorization token will need to employ one of the following methods:
a) Set the token within the environmental variables.
b) Pass the token directly to the function being invoked.
User-guided saving of the token within a file is not explicitly supported. It has been left up to developers to modify and manage it based on their specific requirements.
Tokens passed directly to the function will be given preference over tokens set in the env e.g. if you set token A in the env vars and token B is passed to the function; token B will be the token used.
If you have explicitly set your token in …

Removing support for tokens set via the CLI

---

deeplake/api/dataset.py
deeplake/api/tests/test_dataset.py
deeplake/core/dataset/dataset.py
deeplake/core/meta/dataset_meta.py

Adds a new `dataset.allow_delete = True|False` property to the dataset object which is stored in the dataset_meta.json file. The purpose of the flag is to allow users to explicitly mark a dataset in a way that keeps others from accidentally deleting it.
The default value is "True", but if it is set to False, any attempt to delete or overwrite the dataset will throw an exception until `dataset.allow_delete=True` is set.
The `large_ok` flag still works as before, where datasets larger than 1GB require that flag to delete. But with allow_delete=False set, small datasets can be protected AND large datasets still cannot be deleted even with large_ok=True.
The `force` flag on deeplake.delete() still allows deletion of directories that don't look like a deeplake dataset. But it does not act as …

Added allow_delete flag to dataset

---

deeplake/api/dataset.py
deeplake/client/client.py
deeplake/core/dataset/dataset.py
deeplake/core/tests/test_dataset.py
deeplake/core/version_control/commit_node.py
deeplake/util/tests/test_version_control.py
deeplake/util/version_control.py

If a token is passed as `ds = deeplake.empty(..., token = token)` or `ds = deeplake.load(..., token = token)`, the username didn't get stored in a way that would be used by the `ds.commit("message")` and the log would have the user as "public"
The initial commit fixes the issue by storing it in the `reporting_config.json` which is where it's currently read from, although that's not the best solution. 
The problem is that with concurrent use of dataset objects, data is going to be written badly. 
The 2nd commit changes the method signature to take the username to commit as, which can be pulled from the token as needed rather than using the reporting file ever. If we feel like that is too much of a change, we can revert back to the first commit.

Ensure username is stored for use in commit messages

---

deeplake/api/dataset.py
deeplake/core/dataset/dataset.py

Some messages accidentally still used the `delete_allowed` and `allow_delete(boolean)` pre-release versions of the new `allow_delete=True|False` API.
This PR fixes the messages to give the correct usage. 
Only updates messages, doesn't change the API

Fixed allow_delete wording in messages

---

deeplake/core/chunk/base_chunk.py
deeplake/core/chunk/tests/test_base_chunk.py

A script such as this:
```python
print(ds.str_tensor.numpy())  # prints [['1']]
print(ds.num_tensor.numpy())  # prints [[1]]
print("-----")
ds.append(
{"str_tensor": 2, "num_tensor": 2}
)  # no error, just first tensor is appended as empty string
print(ds.str_tensor.numpy())  # prints [['1']  ['']]
print(ds.num_tensor.numpy())  # prionts [[1] [2]]
print("-----")
ds.num_tensor.append(3)
ds.str_tensor.append(3)  # same here
print(ds.str_tensor.numpy())  # prints  [['1'] [''] ['']]
print(ds.num_tensor.numpy())  # [[1] [2] [3]]
print("-----")
```
silently appends the numbers in str_tensor as empty strings.
This PR makes numbers automatically convert to strings, and throw an error for all other types. This keeps something more unexpected like `ds.str_tensor.append([1,2,3])` from being …

Auto-convert numbers to strings when appending to a text dtype tensor

---

deeplake/api/tests/test_api.py
deeplake/core/chunk_engine.py
deeplake/core/tests/test_dataset.py

When running a script like:
```
ds = deeplake.empty('mem://dummy')
ds.create_tensor('uuid', dtype = np.int32)
ds.uuid.append('asdasd')
ds.uuid.append(1)
```
The htype gets set as "text" even though that isn't compatible with the specified dtype of "int32"
This PR adds validation to the htype computation to ensure it matches the specified dtype

Validate htype vs dtype when detecting htype based on inserted data

---

deeplake/util/tests/test_video.py
deeplake/util/video.py

The video frame lookup does not support lists or other object types, so `ds.video[0][[0,1,2],].numpy().shape` throws an unhelpful error message.
This PR provides a better error message for `lists` in particular and any unsupported type in general. 
Only impacts video parsing

Generate a better error message if a list or other unsupported argument is passed to video.normalize_index

---

deeplake/core/compression.py

Include path in sample decompression error

---

deeplake/core/tensor_link.py

When saving a view, the `sample_info` on some tensors are not correctly saved to the view.
Example:
```
ds = deeplake.load(
"hub://example/my-dataset",
read_only=True,
token=token,
)
view = ds[0:3]
print(view.t1[0].sample_info) # Will print valid sample_info
view.save_view(message='First 3 samples materialized', optimize = True)
view_loaded = ds.load_view(id = ds.get_views()[-1].id)
print(view_loaded.t1[0].sample_info) # Will print empty dict
``` 
This is a more isolated fix than #2791 which updates one place to also know how to deal with Tensor objects rather than just Sample objects. The more isolated fix won't fix any similar problems that live elsewhere, but also doesn't break other code paths like 2791 was.

Fixed tensor "sample_info" on some saved view samples

---

deeplake/client/auth/azure.py

3.8.26 incorrectly assumed azure is installed. It is only available with `pip install deeplake[azure]`
This PR makes the import only happen on functionality use

Don't require azure modules to be installed

---

deeplake/integrations/pytorch/shuffle_buffer.py

fixed tensor size calculation

---

deeplake/client/auth/activeloop.py
deeplake/client/auth/auth_context.py
deeplake/client/auth/azure.py
deeplake/client/client.py

If a user has no token, there is no need to make the API call to /api/user/profile. We can just know their organization is "public" without making the call.
`get_user_organizations()` is the only use of `/api/user/profile`

Avoid making http requests to validate unauthenticated users

---

deeplake/core/query/filter.py
deeplake/core/transform/transform.py

When defining a filter like this:
```
@deeplake.compute
def filter_fn(sample):
return sample.t1.data()["value"] == "Hello"
view = ds.filter(filter_fn())
```
if you forget the `()`in `view = ds.filter(filter_fn())` your data is not filtered. 
This PR looks for that pattern and auto-calls the function for you.
It is still valid to call:
```
def filter_fn(sample):
return sample.t1.data()["value"] == "Hello"
view = ds.filter(filter_fn)
```
which doesn't annotate filter_fn and therefore should NOT have `()` on the value passed to ds.filter()

Check function passed to dataset.filter() is correctly configured

---

deeplake/core/storage/s3.py

retry on get_object_size

---

deeplake/core/storage/s3.py
deeplake/core/storage/tests/test_storage_provider.py

- Increases the minimum number of retries
- Retry on ssl.SSLException
- Backoff retry time on SSLExceptions
Only adds backoff logic for SSLExceptions at this point

Improves S3 retry logic

---

deeplake/core/chunk_engine.py
deeplake/core/index/index.py

When loading chunk files from disk, as memory fills the chunk_engine would wait for there to be room to download. Depending on the overall workload, this waiting could last forever.
This change pops a cached value rather than simply wait

Proactively remove LRU cache values as cache fills

---

deeplake/core/chunk_engine.py
deeplake/util/exceptions.py

Includes the "root cause" reason for a GetChunkError in the error message. 
If the root cause is a GetChunkError also, it goes further up the chain
The string versions of exceptions are not always good and may not be helpful. For example, the KeyError I tested with only listed the key with no other information. Other random causes for GetChunkError may be more helpful, or not

Improved message for GetChunkError

---

deeplake/core/storage/gcs.py
deeplake/enterprise/dataloader.py

added handling of object dtype in decode method data

---

deeplake/core/dataset/dataset.py

Min max calculation

---

deeplake/api/dataset.py
deeplake/core/compression.py
deeplake/core/sample.py

Previously, we just looked at the end of the file string to determine the filetype in a `ds.tensor_name.append(deeplake.read(...))` call.
For data read from URLs with query parameters, the end of the path was not necessarily the extension. Also, with URLs in general the path does not necessarily include the extension.
This PR removes any query parameters from the path when checking for a recognized extension, and also checks more header data to detect filetypes than the images we did previously.
Not all types can be detected by headers, but most are now

Improve file type detection using headers and ignoring URL arguments

---

deeplake/api/dataset.py
deeplake/core/dataset/dataset.py
deeplake/core/tensor.py
deeplake/core/transform/transform.py
deeplake/enterprise/dataloader.py
docs/source/Datasets.rst

- Improvements to the API reference to clarify key concepts and remove errors.
- Removal of unused imports in places where this was noticed

Clarifications to Docs

---

deeplake/core/dataset/dataset.py

Previously, sample_info was only stored for the following htypes:
- image
- audio
- video
- dicom
- point_cloud
- mesh
- nifti
This PR adds "segment_mask" to that list
Will not create the sample_info for existing segment_mask tensors. If you need sample_info for a segment_mask you will need to create a new tensor and copy the data over

Store sample_info for segment_mask htypes

---

deeplake/auto/structured/dataframe.py
deeplake/auto/tests/test_ingestion.py
deeplake/core/dataset/dataset.py

-- Added support for datetimes in the input dataframe.
-- Switch Nan replacement on a column-by column basis which makes it more robust.

Added support for dataframes with datetime

---

deeplake/api/dataset.py
deeplake/core/index_maintenance.py
deeplake/core/vectorstore/test_deeplake_vectorstore.py

This PR avoids an error when creating a view of a dataset group, like this:
```
ds = deeplake.empty("group_test", overwrite = True)
ds.create_tensor("group/test")
ds["group/test"].extend([np.random.rand(100,) for i in range(10000)])
ds.commit()
view = ds["group"][0:10]
view.save_view(id="firstdbf9474_positive_labels", optimize=True, num_workers=0)
```

Handle creating a view of a tensor group

---

deeplake/core/vectorstore/test_deeplake_vectorstore.py
deeplake/core/vectorstore/vector_search/filter/filter.py
deeplake/core/vectorstore/vector_search/filter/test_filter.py
deeplake/core/vectorstore/vector_search/indra/search_algorithm.py

- Added dictionary based filtering where if target is a list, it's compared via IN
- Cleaned up tests slightly, and removed TQL string comparisons in some tests. The query results are either right or wrong, and should be assessed via output correctness. We likely shouldn't test string parsing or TQL syntax in the vector store module.

Added dictionary based filtering for IN

---

deeplake/auto/unstructured/kaggle.py

Use subprocess.Popen instead of os.system

Improve kaggle system call

---

deeplake/integrations/mmseg/mmseg_.py

allow decode method for images tensor in mmseg

---

deeplake/auto/unstructured/kaggle.py
deeplake/core/dataset/indra_tensor_view.py
deeplake/core/tests/test_indra_dataset.py
deeplake/core/version_control/test_version_control.py
deeplake/enterprise/test_pytorch.py
deeplake/enterprise/test_query.py
deeplake/integrations/tests/test_pytorch.py
deeplake/tests/common.py

[DEEP-202] fix string data cutting issue

---

deeplake/enterprise/convert_to_libdeeplake.py

[DEEP-208] provide creds dict with non empty strings

---

deeplake/core/tensor.py
docs/source/Tensors.rst

added documentation for ```tensor.create_vdb_index``` function

create vdb index doc

---

deeplake/core/dataset/dataset.py
deeplake/core/query/test/test_query.py

A script like this unexpectedly overwrites the existing view:
```
ds = deeplake.empty("debug_branch_view", overwrite=True)
ds.create_tensor("test")
ds.extend({"test": np.random.rand(100, 100, 3)})
ds.commit("first_commit")
view_1 = ds[0:10]
view_1.save_view(id = "view_id")
view_2 = ds[20:30]
view_2.save_view(id = "view_id")
print(ds.get_views())
print(len(ds.get_views()))
```
This PR change the 2nd save_view to raise an exception

Raise exception if a view to save's id already exists

---

deeplake/client/client.py

Retry calls to get credentials from the backend 5 times if a connection error occurs

Retry connection errors on credentials requests

---

deeplake/api/tests/test_api.py
deeplake/core/dataset/dataset.py
deeplake/core/tests/test_query.py

Class label test fix

---

deeplake/api/tests/test_api_with_compression.py
deeplake/core/chunk_engine.py

fixed optimize for image.rgb and image.gray htypes

---

deeplake/integrations/labelbox/labelbox_.py
deeplake/integrations/labelbox/labelbox_converter.py
deeplake/integrations/labelbox/labelbox_metadata_utils.py
deeplake/integrations/labelbox/labelbox_utils.py
deeplake/integrations/tests/test_labelbox.py

V3 labelbox api export improvements

---

python/deeplake/__init__.py
python/deeplake/__init__.pyi
python/deeplake/ingestion/__init__.py
python/deeplake/ingestion/coco/from_coco.py
python/deeplake/integrations/mmdet/mmdet_.py
python/deeplake/integrations/mmseg/mmseg_.py
python/deeplake/types.py
python/deeplake/types.pyi

v4.1.4 Release.

---

python/deeplake/__init__.py
python/deeplake/__init__.pyi
python/deeplake/schemas.pyi
python/deeplake/types.py
python/deeplake/types.pyi

- Support [biomedical data types - dicom and nifti](https://docs.deeplake.ai/latest/api/types/#deeplake.types.Medical)
- Support [point data type](https://docs.deeplake.ai/latest/api/types/#deeplake.types.Point)
- Ability to run index search on virtual columns
- 2x speedup in inverted index generation

v4.1.5 Release

---

deeplake/integrations/labelbox/labelbox_converter.py
deeplake/integrations/labelbox/labelbox_utils.py
deeplake/integrations/tests/test_labelbox.py

Labelbox no frame interpolation in project json

---

deeplake/integrations/labelbox/labelbox_.py
deeplake/integrations/tests/test_labelbox.py

remove labelbox client arg from labelbox integration functions

---

deeplake/integrations/labelbox/labelbox_.py
deeplake/integrations/labelbox/labelbox_azure_utils.py

add labelbox iam integration support
